### ISSUE TITLE
Link a scheduled workflow execution to its originator

### ISSUE THREAD

**Issue by lorensr** [temporalio/ui#1043]
## Is your feature request related to a problem? Please describe.

I left a schedule running and I want to terminate it, but my workflows page is full of the scheduled workflows, not the originator that I need to terminate.

## Describe the solution you'd like

A link at the top of the scheduled workflow detail pages, similar to parent links from children workflows.

## Additional context

In this case, the originator Workflow Id is `temporal-sys-scheduler:sample-schedule`, which we can construct by prefixing `temporal-sys-scheduler:` to the value of the first search attribute below (@dnr is this the best place to look it up?): 

![image](https://user-images.githubusercontent.com/251288/211944109-fe2e5287-36da-4036-b896-98e361f6d429.png)

**Comment by dnr** [comment]
The originator is not a workflow, it's a schedule. The fact that a schedule is implemented by a workflow is a private implementation detail that you shouldn't see or depend on. The id of the schedule is in that search attribute, yes, and you can use that to link to the schedule detail page.

**Comment by Alex-Tideman** [comment]
Link for schedule is included in Relationships accordion
