### ISSUE TITLE
Possible security issue with text injection

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#1142]
Community slack thread: https://temporalio.slack.com/archives/C011AAP3GFP/p1676362992794949

User noticed that any invalid url user types in shows as message on the 404 error page thats displayed for that url.
Example given by user: http://localhost:8081/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM

shows 

<img width="1193" alt="Screen Shot 2023-02-14 at 8 33 08 AM" src="https://user-images.githubusercontent.com/119422/218753566-820f4105-3d91-4a05-a94e-49ff1da14de9.png">

This raises concerns about possible text injection attacks.

**Comment by stevekinney** [comment]
While, I don't believe that route is shown on 404 pages anymore, I also just double checked and made sure there wasn't a concern. Rendered text is always sanitized—even in the URL itself.

For example: Attempted to do `http://localhost:3000/namespaces/default/<script>alert('uh oh');</script>` will result in `http://localhost:3000/namespaces/default/%3Cscript%3Ealert('uh%20oh');%3C/script%3E`.

Even if you manage to use a URL segment that is rendered on the page, it's properly escaped. For example, if you navigate to `http://localhost:3000/namespaces/%3Cscript%3Ealert('oh%20no')(%3C%2Fscript%3E/workflows`, you'll see the following.

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/251000/218772743-89acdd40-9815-4dc0-beed-f3104cb6cf16.png">

This applies to query parameters as well. Navigating to `http://localhost:3000/namespaces/default/workflows?search=advanced&query=%3Cscript%3Ealert%28%27oh+no%27%29%3B%3C%2Fscript%3E` will not cause the input to be evaluated.

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/251000/218773121-46a544dc-237d-4ba3-b402-2b36acc7549d.png">
