### ISSUE TITLE
The completed workflows are not showed in temporal-ui

### ISSUE THREAD

**Issue by tanbt** [temporalio/ui#1183]
**Describe the bug**
I'm new to Temporal and not sure if this is a valid issue, but the Recent Workflow page only shows workflows within the last 1 or 2 days, older completed workflows can't be seen elsewhere in temporal-ui.

**To Reproduce**
* Create some workflows and complete them, make sure the Status show "Completed" green text
* Leave it there for 3-4 days

**Expected behavior**
All the workflows should be visible.

**Actual behavior**
The workflows are not showed anymore.

**Screenshots**
![image](https://user-images.githubusercontent.com/4935326/221204434-a6ea7585-2418-4eb2-b9f1-00ac5a18b241.png)

**Desktop (please complete the following information):**
Run with Docker using `docker-compose-postgres.yml` config.

**Additional context**
I'm not sure if this is an expected behaviour and don't know how can I see all the history workflows.

**Comment by Alex-Tideman** [comment]
Hey @tanbt, thanks for the issue and welcome to using Temporal! Do you know what your retention period is set for? If it's set for 3 days, any workflows older than that will not be returned by the API.

**Comment by tanbt** [comment]
Hi Alex, yes I believe that is the issue because I didn't change retention configuration (it's new to me), and the default is 3 days. I changed to 30 days hopefully it would work. Thanks for the quick help!

**Comment by Alex-Tideman** [comment]
👍 I'm going to close this issue then but feel free to reopen if you have any issues.
