### ISSUE TITLE
UI - Inconsistent dates on schedulers

### ISSUE THREAD

**Issue by nicovak** [temporalio/ui#1215]
**Describe the bug**

**To Reproduce**

1 - Add a Scheduler
2 - Look for the difference on dates for "upcoming runs" between the list view and show view (correct in the show only)

**Screenshots**

- List
![Capture d’écran 2023-03-16 à 12 17 45](https://user-images.githubusercontent.com/6214452/225601554-9134c510-f4fa-4a67-a945-bf133d3b165f.png)

- Show
![Capture d’écran 2023-03-16 à 12 20 29](https://user-images.githubusercontent.com/6214452/225601735-e98c7cb6-b8af-4c5f-b4bf-60267c61bbcc.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 111

**Comment by Alex-Tideman** [comment]
Related to https://github.com/temporalio/temporal/pull/4128

**Comment by dnr** [comment]
Note that that PR applies to the period in between the schedule being created and the internal workflow actually starting, which should be very quick (<1s). So it would be hard to observe, unless the internal worker is broken somehow
