### ISSUE TITLE
Support Relative URLs in SSO for OIDC Providers Like Vault

### ISSUE THREAD

**Issue by zboralski** [temporalio/ui#1237]
Temporal UI's SSO implementation expects absolute URLs when integrating with OIDC providers. However, some providers, such as Vault, use relative URLs for all endpoints listed in their .well-known/openid-configuration.

I suggest adding support for relative URLs in the SSO configuration to enhance compatibility with OIDC providers like Vault. To help with this, I plan to submit a PR tomorrow addressing this issue.

Please let me know if you need any additional information or clarification. Thank you for your continuous efforts in improving Temporal.

**Comment by zboralski** [comment]
It seems that Vault automatically sets the issuer URL using an absolute URL only when it's configured as a High Availability (HA) cluster.

By explicitly configuring the issuer URL, the issue can be resolved:

```bash
vault write identity/oidc/provider/temporal \
    allowed_client_ids="${CLIENT_ID}" \
    scopes_supported="user,groups" \
    issuer="https://vault.example.com"
```

This configuration ensures that the issuer URL is set to an absolute URL, allowing proper integration with Temporal UI's SSO. I hope this information proves useful for others facing a similar situation.

**Comment by feedmeapples** [comment]
@zboralski thx for the details. cc @robholland
