### ISSUE TITLE
error":"code=500, message=invalid returnUrl: does not match expected host temporal-web.temporal:8080"

### ISSUE THREAD

**Issue by mbkh68** [temporalio/ui#1272]
Receiving this error after update UI to version 2.13.3, was fine on version 2.11.1 (using keycloak), no  other configuration changes, only image update

**Comment by mbkh68** [comment]
it turned out that issue caused after this PR https://github.com/temporalio/ui/pull/1157/commits
my problem got fixed by updating our reverse proxy to pass host herder. closing

**Comment by advdv** [comment]
For us this is an issue, we would like to serve the temporal ui on the edge. The edge forwards to our AWS ALB, which is not publicly reachable. Our edge and the ALB run on completely different domains and we cannot depend on the host header being forwarded.
