### ISSUE TITLE
[Bug] Custom search attributes not showing up in UI

### ISSUE THREAD

**Issue by mjameswh** [temporalio/ui#1274]
### Describe the bug

Custom search attributes do not show up in UI, even though they do appears in CLI.

### Minimal Reproduction

1. Start a dev server:

```
temporal server start-dev
```

2. From a different terminal, add a custom attribute.

```
temporal operator search-attribute create --namespace default --name CustomAttr1 --type Text --yes
sleep 10

temporal operator search-attribute list --namespace default
# Observe that CustomAttr1 appears in the list of attributes
```

3. Visit `http://127.0.0.1:8233/namespaces/default`, and observe that `CustomAttr1` is not listed.

### Environment/Versions

- Tested with CLI 0.8.0, but investigation suggests that this is independent of CLI

**Comment by mjameswh** [comment]
Seems like the issue is that UI is still using `workflowservice/GetSearchAttributes` (which is not namespace aware) rather than the new `operatorservice/ListSearchAttributes` (which is now the correct way to obtain these info since addition of advanced visibility support on SQL backends in server).

**Comment by sumitshinde-84** [comment]
I would like to work on this issue,  can you please assign it to me?
