### ISSUE TITLE
Docker:  move config template directory -- Security Context

### ISSUE THREAD

**Issue by cxtuttle** [temporalio/ui#1285]
This issue is opened here since you can not open an issue under ui-server where the Docker images are built from.

Currently the entry point script does:  _dockerize -template ./config/config_template.yaml:./config/docker.yaml_

If the config template was moved to say _./config-template/config_template.yaml_

Than within Kubernetes it would be possible to run best practices of a security context i.e:

 containers:
      - name: temporal-ui
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: **true**
          capabilities:
            drop:
               - all
...
        volumeMounts:
          - name: config-volume
            mountPath: /home/ui-server/config
      volumes:
        - name: config-volume
          emptyDir:
            sizeLimit: 10Mi

With the current setup it is not possible to set the Root filesystem read-only as it needs to read and write to the same directory.

**Comment by robholland** [comment]
I understand the desire. Unfortunately this would be a backward incompatible change for people who are mounting a volume for the config file so we'll need to think if we can work around that.
