### ISSUE TITLE
Links to workflows in a Workspace table view should be "real" link elements

### ISSUE THREAD

**Issue by deltamualpha** [temporalio/ui#1324]
**Describe the bug**

It used to be that table elements were `<a>` elements, so the normal ways browsers know to interact with a link element worked -- you could right-click them to open in a new tab, for example, or just hold down cmd and click them to open a number of them at once. After the recent updates to Svelte, however, it looks like the table elements are just non-semantic `<span>` elements, which reduces accessibility on a number of levels.

<img width="506" alt="Screenshot 2023-04-21 at 10 33 22 AM" src="https://user-images.githubusercontent.com/2105458/233662903-8d0710d1-b9dc-412b-953f-36ec55b732b7.png">

**To Reproduce**

Open a namespace and attempt to interact with a table row as if it were a real link (i.e. right-click to open it in a new tab).

**Expected behavior**

Make things that look like links, actually links.

**Desktop (please complete the following information):**

- OS: Mac, but this is irrelevant.
- Browser: Chrome
- Version: 2.14.0

**Comment by stevekinney** [comment]
Good catch! Thanks!
