### ISSUE TITLE
[Feature Request] Button to fail a pending activity

### ISSUE THREAD

**Issue by sw-yx** [temporalio/ui#134]
### Is your feature request related to a problem? Please describe.

Feature request for the UI:
Add button to fail a pending activity.
This is useful when a worker is restarted while processing an activity with a long start to close timeout and a user want to retrigger the activity.
There's an RPC for that.

https://github.com/temporalio/api/blob/e57bfa08cf7409d2b15a32fa06ebb079f9d1c39c/temporal/api/workflowservice/v1/service.proto#L173

https://temporaltechnologies.slack.com/archives/C018F52DUKU/p1635950521093300

**Comment by stevekinney** [comment]
@feedmeapples Is this exposed in the API currently?

**Comment by canvanooo** [comment]
@sw-yx I've moved this feature request to the UI backlog, will close this here.
