### ISSUE TITLE
When the workflows search box is in focus, the enter key does not submit the search query

### ISSUE THREAD

**Issue by twexler** [temporalio/ui#1347]
**Describe the bug**
When the workflows search box is in focus, the enter key does not submit the search query. Instead, nothing happens.

**To Reproduce**

1. Go to the Workflows page
2. Enter a query into the search box
3. Press enter

**Expected behavior**
Enter should trigger the UI to initiate the search

**Desktop (please complete the following information):**

- OS: macOS 13.3.1
- Browser Chrome 112.0.5615.137 (Official Build) (arm64)
- Version 2.9.1

**Comment by Alex-Tideman** [comment]
I've included a screen recording showing this works in latest release (2.14.0). I'm going to close this but if you are able to recreate please reopen.

https://github.com/temporalio/ui/assets/7967403/ff14314a-2e8f-4e62-b453-1efe5a7902a8
