### ISSUE TITLE
[Feature Request] Show hints for common failures

### ISSUE THREAD

**Issue by feedmeapples** [temporalio/ui#136]
### Is your feature request related to a problem? Please describe.

Some workflow task failures are expected and benign, though still give a sense of something going terribly wrong

### Describe the solution you'd like

@Sushisource 

> UI should show a hint about UNHANDLED_COMMAND WFT failures explaining that they are typically benign:
> 
> any time there is a WFT failed event with this cause https://github.com/temporalio/api/blob/ff5e03eb3b7315c3470e91338c7fe97b2619cfc6/temporal/api/enums/v1/failed_cause.proto#L36 we should show a little bit of helpful info like "this is expected if something new happened between the worker taking the WFT and completing it

### Additional context

@mfateev 

> Random idea is to have explanation of every type of event and failure type as part of the UI

**Comment by feedmeapples** [comment]
cc @canvanooo would like mockups for Maxim's suggestion to "have explanation of every type of event and failure type as part of the UI"

**Comment by canvanooo** [comment]
Yes, I am on it!!
