### ISSUE TITLE
Dockerhub release image missing

### ISSUE THREAD

**Issue by arrowcircle** [temporalio/ui#1369]
**Describe the bug**
Dockerhub misses latest releases. There are 2.15.1, 2.15.2 and 2.15.3 releases on the github, but only 2.15.0 image in the dockerhub.

**To Reproduce**

1. Go to https://github.com/temporalio/ui/releases and note latest releases with version tags
2. Go to https://hub.docker.com/r/temporalio/ui/tags and note, that some releases are missing

**Expected behavior**
Dockerhub should have the same image tags as github releases.

**Comment by robholland** [comment]
Releases are built from: https://github.com/temporalio/ui-server which has different versions.
