### ISSUE TITLE
Allow Multiple Workflow Events to be Expanded

### ISSUE THREAD

**Issue by Albert-Coding** [temporalio/ui#1449]
## Is your feature request related to a problem? Please describe.
When debugging a workflow run, it would be nice to see more than one expanded event history item.  This would especially be useful when one wants to see an activity input and the activity output.

## Describe the solution you'd like
Be able to expand any number of of event items.  That said, there should also be a `collapse` all feature-- though one could reload the URL to close all expanded items.

## Describe alternatives you've considered
Use 2 web browser tabs to be able to see both the inputs and outputs.

**Comment by Alex-Tideman** [comment]
Fixed with https://github.com/temporalio/ui/pull/1694
