### ISSUE TITLE
Remove Github Dependency for the UI

### ISSUE THREAD

**Issue by sonalparab** [temporalio/ui#1465]
## Is your feature request related to a problem? Please describe.

We are running version 2.14.0 of the Temporal UI.
The UI has a dependency on Github (a GET request to https://api.github.com/repos/temporalio/ui-server/releases), so when Github is down the UI does not load until the request to the Github API times out, causing the page to take 100+ seconds to load.

## Describe the solution you'd like

Remove this Github API request if it is not used for anything in the UI. Alternatively make this request asynchronous so it does not block the page from loading.

## Additional context

This is where the Github API request is happening: 
<img width="557" alt="image" src="https://github.com/temporalio/ui/assets/29069327/a332651b-0c22-425e-b693-1ea0e460b897">

**Comment by stevekinney** [comment]
I just spent a little bit of time looking into this. It looks like it _is_ asynchronous but because of `async`/`await`, it still holds everything up. I'll get this queued up for our next sprint.

**Comment by stevekinney** [comment]
We just opted to remove this functionality in #1609. ☺️
