### ISSUE TITLE
Please provide two additional ways to visualize the workflow history

### ISSUE THREAD

**Issue by nitinmuppalaneni** [temporalio/ui#1475]
## Is your feature request related to a problem? Please describe.

Please provide a DOT graph view and a table view of the workflow history.

## Describe the solution you'd like

The current workflow history in the web UI is handy and shows events in time order. During debugging issues, I find it helpful to see the events in a table view. It would be nice to see the information in time-ordered table form in the web UI. Also please consider adding a DOT graph view of the events.

## Describe alternatives you've considered

I currently do this by downloading the JSON formatted history and viewing it in table form using pandas.

## Additional context

To see which worker is handling the different events, I use pandas. Here is a snippet.

```
import pandas as pd

evt_df = pd.json_normalize(pd.read_json('~/Downloads/4008bf20-031f-47cc-afd7-75f14c9fdb61_events.json')['events'])
identity_df = evt_df.filter(like='identity').apply(lambda x: ','.join(x.dropna().astype(str)), axis=1).to_frame('identity')
evt_df.filter(items=['eventId', 'eventTime', 'eventType', 'taskId']).join(identity_df, how='outer')
```

**Comment by Alex-Tideman** [comment]
Thanks for the suggestion! 

We recently added a new visualization for workflow history that you can view if you add the `labs=true`  url param on the Workflow history page (`.../history?labs=true`). But I'll definitely check out the panda and we are very much looking into adding more visualizations.
