### ISSUE TITLE
Allow filtering/excluding a combination of event types

### ISSUE THREAD

**Issue by jadami10** [temporalio/ui#1534]
## Is your feature request related to a problem? Please describe.

My specific issue is since we've started using signals, the "compact" view has become a lot more cluttered. What I want to see is "everything besides signals", but you can only filter out by 1 event type at a time. Also, the compact view shows child workflows but doesn't let you filter to those. You can only filter to child workflows in the history view.

## Describe the solution you'd like

Ideally the workflow events/event type filters would show all types and allow selecting a combination of them. I think a typical filter pattern is to have check boxes next to each item, a "select all" button, and an "only" option next to each type. But really just checkboxes would solve this.

**Comment by Alex-Tideman** [comment]
https://github.com/temporalio/ui/pull/1806
