### ISSUE TITLE
Click Continue to SSO button twice after logout or session timeout

### ISSUE THREAD

**Issue by michaeldop** [temporalio/ui#1594]
**Describe the bug**
It appears that when the `returnUrl` is anything but the baseUrl, for example `https://temporal-ui.domain.com/login?returnUrl=https%3A%2F%2Ftemporal-ui.domain.com%2Fnamespaces%2Fdefault%2Fworkflows`, Temporal UI requires you to click on the "Continue to SSO" button twice.

**To Reproduce**

1. Go to temporal login page and click on 'Continue to SSO'
2. See that you are successfully logged in and are on the workflows page
3. Click the top left corner drop down and 'Log out'
4. Click on 'Continue to SSO'
5. See an unauthorized error (see screenshots below)
6. Click on 'Continue to SSO' again 
7. See that you are succesfully logged in

**Expected behavior**
I would expect to only have to click on the "Continue to SSO" button once and after successful authentication go whatever `redirectUrl` was set to

**Screenshots**
First time clicking "Continue to SSO" redirects back to this page with "unauthorized"
![Screenshot 2023-08-25 at 1 52 01 PM](https://github.com/temporalio/ui/assets/64210583/fcac252b-c429-4f83-a4ab-c7697cb59319)

There is a 401 error being thrown here after clicking on 'Continue to SSO'
![Screenshot 2023-08-28 at 9 52 01 AM](https://github.com/temporalio/ui/assets/64210583/268d5642-7016-4e7c-9e02-21645d0942bc)

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome
- Version: 116

**Additional context**
 - Temporal UI 2.18.0

**Comment by joshbranham** [comment]
We are also noticing this, as well as the `returnUrl` being perpetually appended to the URL when you click the Temporal logo in the top left of the UI on the login screen.

**Comment by MB175** [comment]
This issue is caused by the search-attributes endpoint, which is called soon before the auth token is set as a header parameter.

`/api/v1/namespaces/default/search-attributes?`

Since the UI is receiving a 401 Statuscode it falls back to the login page. To prove that the search-attributes endpoint is the issue, it can simply be blocked out in Chrome, and the login process works flawlessly.

![Bildschirmfoto 2024-01-04 um 11 06 18](https://github.com/temporalio/ui/assets/57674787/71197d47-d67b-4403-809d-c8f5c5fe86cf)

**Comment by MB175** [comment]
Debugging that behaviour will require the ui-server, since the vite debugging must be done over the vite port not the build ui which is served from the asset folder by the ui-server a proxy logic must be added into the vite project which redirects all calls containing /auth to the ui-server

**Comment by MB175** [comment]
https://github.com/temporalio/ui/blob/1c5bf19819b6b6f57b22f000fe88521578782888/src/routes/(app)/namespaces/%5Bnamespace%5D/%2Blayout.ts#L10

The call to fetch the attributes is happening before the AuthUser is set in the key value store

https://github.com/temporalio/ui/blob/1c5bf19819b6b6f57b22f000fe88521578782888/src/routes/(app)/%2Blayout.ts#L27

If auth is enabled the fetch should check if the token is already set
