### ISSUE TITLE
The execution duration filter doesn't work as expected

### ISSUE THREAD

**Issue by ksharinarayanan** [temporalio/ui#1640]
**Describe the bug**
We have an option to filter down based on the execution duration. But when I select ExecutionDuration < 15, it shows workflows that ran longer than 15 seconds as well, and it also removed some of the workflows with less than 15 seconds. What logic is being applied here to filter the workflows based on ExecutionDuration?

**To Reproduce**

1. Go to Filter, and select ExecutionDuration < 15

**Expected behavior**
The search results should be consistent.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version 2.18.1

Please let me know if anything else is required.

Thanks

**Comment by Alex-Tideman** [comment]
If you look at https://docs.temporal.io/visibility#default-search-attributes, you will see that Execution Duration is in nanoseconds. So ExecutionDuration < 15000000000 should be the correct query.
