### ISSUE TITLE
`ChildWorkflowExecutionFailed` events not shown in "compact" history view

### ISSUE THREAD

**Issue by kheyse-oqton** [temporalio/ui#1681]
**Describe the bug**
`ChildWorkflowExecutionFailed` events are not shown in "compact" view.
I would expect to see them under the compacted item for the relevant child workflow, but I only see `ChildWorkflowExecutionStarted` and `StartChildWorkflowExecutionInitiated` there.
The `ChildWorkflowExecutionFailed` event is visible in the "long" history view.

**To Reproduce**
Browse to a workflow with failed child workflow, and click on the "Compact" view icon.

**Expected behavior**
I expect to see 3 events: `StartChildWorkflowExecutionInitiated`, `ChildWorkflowExecutionStarted` and  `ChildWorkflowExecutionFailed`.

**Screenshots**
<img width="907" alt="image" src="https://github.com/temporalio/ui/assets/35029144/d5024b2c-1e68-44e1-a0b5-f1147d70afc8">

**Desktop (please complete the following information):**

- OS: OS X 13.6
- Browser Firefox
- Version 118.0.1

**Comment by Alex-Tideman** [comment]
Fixed in 2.26.0
