### ISSUE TITLE
I would like to see the localActivity name in the UI

### ISSUE THREAD

**Issue by antmendoza** [temporalio/ui#1689]
## Is your feature request related to a problem? Please describe.

When I have a local activity, the name of the local activity is not shown in the UI, see screenshot below. 

- typescript 

<img width="1057" alt="Screenshot 2023-10-16 at 09 49 51" src="https://github.com/temporalio/ui/assets/514932/5a99f587-0c14-4bbe-aa52-5966cca7ac11">

- java

<img width="1065" alt="Screenshot 2023-10-16 at 09 50 07" src="https://github.com/temporalio/ui/assets/514932/4206dd58-eab6-4053-8c53-c23b0cbc11ee">

**Comment by Alex-Tideman** [comment]
Hey @antmendoza, what would you expect to see here? The marker name of a local activity is LocalActivity, so not sure what else we can show.

**Comment by antmendoza** [comment]
Hi @Alex-Tideman 
I think the user expect to see the activity name, in this case "ComposeGreeting", attaching the workflow history produced by the Java sdk 

[8e701c85-ad10-44b3-ba55-9225ae87c285_events.json](https://github.com/temporalio/ui/files/13206158/8e701c85-ad10-44b3-ba55-9225ae87c285_events.json)

<img width="1170" alt="Screenshot 2023-10-30 at 14 20 28" src="https://github.com/temporalio/ui/assets/514932/6f0b7115-0603-454b-8e52-9ec13d780a43">

**Comment by zuodimiaoyun** [comment]
Hi @Alex-Tideman 
I have the same situation, I want to use LocalActivity to improve performance, but I can't see the name on the UI so I can directly see what the workflow is doing.

**Comment by zuodimiaoyun** [comment]
found the pull request [Add Local Activity support and show activity type for Local Activities in event history](https://github.com/temporalio/ui/pull/930) to do this, but now it's gone . Can we bring it back?

**Comment by antmendoza** [comment]
thank you @zuodimiaoyun 

cc @Alex-Tideman

**Comment by Alex-Tideman** [comment]
Add the fix here: 

https://github.com/temporalio/ui/pull/1795
