### ISSUE TITLE
Queries are not working

### ISSUE THREAD

**Issue by diezfx** [temporalio/ui#1767]
**Describe the bug**
With the latest Version queries are not shown correctly anymore.

Instead the UI fails and in the network tab the following error is received:
{
  "code": 3,
  "message": "unknown queryType %40%40temporal-internal__list. KnownQueryTypes=[__stack_trace __open_sessions]",
  "details": [
    {
      "typeUrl": "type.googleapis.com/temporal.api.errordetails.v1.QueryFailedFailure",
      "value": null
    }
  ]
}

**To Reproduce**
Open the detailed view for worklows, then click on queries

**Expected behavior**
The list of queries is shown

- Version 21.3

**Comment by Alex-Tideman** [comment]
That error is expected (it's how we get our list of queries). I am able to view queries as normal.
