### ISSUE TITLE
Feature Request: Timeline view allows navigation to child workflows

### ISSUE THREAD

**Issue by edclement** [temporalio/ui#1786]
## Is your feature request related to a problem? Please describe.

The timeline view is great. However, clicking on a child workflow from the timeline view does nothing. When there are lots of child workflows named the same, it's difficult to determine which child workflow id lines up with the visual representation in the timeline view.

## Describe the solution you'd like

Clicking on a child workflow in the timeline view opens that workflow in a new tab.

## Describe alternatives you've considered

Using the "Relationships" > "Children" table to select a child workflow. But you loose the context of when that workflow started/stopped and how long it took in relation to other child workflows.

## Additional context

None.

**Comment by Alex-Tideman** [comment]
Added in new Timeline view (can also view Timeline of child directly without navigating)
