### ISSUE TITLE
[Feature Request] Support signaling workflows

### ISSUE THREAD

**Issue by feedmeapples** [temporalio/ui#182]
### Is your feature request related to a problem? Please describe.

Signaling workflows directly from the UI can simplify/speed up development, facilitate testing etc

### Describe the solution you'd like

1. An input for selecting the signal and a json input
2. Optionally we can look into customizing the input UI depending on the input data type (or look for other ways to achieve that)

### Additional context

User request: https://community.temporal.io/t/web-ui-with-built-in-user-input-components/3651

**Comment by stevekinney** [comment]
@feedmeapples Do we have this API exposed in @temporalio/ui-server?

**Comment by feedmeapples** [comment]
it is not currently exposed, adding

**Comment by axelyung** [comment]
Would be great to land this feature!
