### ISSUE TITLE
Temporal UI Login Restriction for specific ppl

### ISSUE THREAD

**Issue by shanmukha511** [temporalio/ui#1856]
**Describe the bug**

Hi Team,

We are running temporal in kubernetes cluster and enabled sso for the same. But everyone in our team can login and access who has url with them. Is ther any way we can restrict/allow Temporal login access for specific people?

**Comment by Alex-Tideman** [comment]
https://docs.temporal.io/self-hosted-guide/security#authorization

You can use the ClaimMapper and Authorizer plugin for this.
