### ISSUE TITLE
Show the arguments that are associated with a schedule

### ISSUE THREAD

**Issue by antmendoza** [temporalio/ui#1857]
## Is your feature request related to a problem? Please describe.

Users want to see in the UI the arguments associated with a schedule. The arguments that are passed to the workflow execution when it's triggered.

**Comment by alexrejto** [comment]
This would also be helpful for our team. Ideally we could set these arguments on schedule creation and mutate them in the edit schedule view.

**Comment by Alex-Tideman** [comment]
In v2.26.0
