### ISSUE TITLE
Temporal is unable to upsert a stringified JSON into seach attribute of Type INDEXED_VALUE_TYPE_TEXT

### ISSUE THREAD

**Issue by ashish-zoop** [temporalio/ui#1860]
**Describe the bug**
Using operator service if we create a search attribute of type: IndexedValueType.INDEXED_VALUE_TYPE_TEXT, and further during workflow run, if we try to store a stringified JSON as the value - temporal server throws an error.

**To Reproduce**

1. create a search attribute - of type - IndexedValueType.INDEXED_VALUE_TYPE_TEXT
2. store a stringified JSON into it while workflow run
3. Observer server logs
4. See error such as: "error":"pq: syntax error in tsvector:...."

**Expected behavior**
Stringified JSONs should be store-able in TEXT type of search attributes

**Screenshots**
Below

**Desktop (please complete the following information):**

- OS: macOS
- Browser: brave
- Version : not sure

**Additional context**
None

![image (3)](https://github.com/temporalio/ui/assets/110413261/f1722038-8fa6-4514-b48f-e7bc09e4e674)

**Comment by Alex-Tideman** [comment]
@ashish-zoop This isn't an issue with UI, please open in our server repo https://github.com/temporalio/temporal/issues
