### ISSUE TITLE
Missing docker image for release 2.23.5

### ISSUE THREAD

**Issue by thameezb** [temporalio/ui#1880]
**Describe the bug**
Docker image is not published for latest release

**To Reproduce**

1. `docker pull temporalio/ui:2.23.5`

**Expected behavior**
Image being pulled successfully

**Comment by Alex-Tideman** [comment]
Make sure you read on our section on releases: https://github.com/temporalio/ui?tab=readme-ov-file#releases

2.23.0 is the latest docker image. We will be releasing a new one this week. Thanks!
