### ISSUE TITLE
Safari: missing csrf token in request header

### ISSUE THREAD

**Issue by ManuverGujjar** [temporalio/ui#1894]
**Describe the bug**
When I try to terminate a workflow. It works fine on Chromium based browser and Firefox but in Safari it gives CSRF token error

**To Reproduce**

1. Go to temporal web in Safari browser
2. Try to terminate a running WF

**Expected behavior**
WF should terminate 

**Screenshots**
<img width="1154" alt="Screenshot 2024-02-29 at 23 03 29" src="https://github.com/temporalio/ui/assets/39888253/23431dfa-26db-429e-be8f-1515de58331d">

**Desktop (please complete the following information):**

- OS: macOs
- Browser safari
- Version 17.3.1 (19617.2.4.11.12)

**Additional context**
NA

**Comment by Alex-Tideman** [comment]
You can fix this for local development with Safari by setting TEMPORAL_CSRF_COOKIE_INSECURE to true

cors:
  cookieInsecure: {{ default .Env.TEMPORAL_CSRF_COOKIE_INSECURE "false" }}
