### ISSUE TITLE
Cannot view old run history if there are multiple runs with same workflow ID

### ISSUE THREAD

**Issue by scwhaley** [temporalio/ui#1901]
**Describe the bug**
Given two workflow executions with the same workflow id and unique run ids, you cannot view the history of the old run, only the most recent run.

**To Reproduce**

1. Execute a workflow with the same workflow id twice so that each run has the same workflow id, but different run ids
2. Open the UI workflows page.
3. In the RunID column, click the run id of the earliest execution of the workflow.
4. The resulting page shows the history of the most recent run, not the run you selected. 

**Expected behavior**
I should be able to click on a specific run of a workflow (even if there are multiple runs for the same workflow id) and see the history for that particular run, not the most recent run.

**Screenshots**
<img width="1726" alt="image" src="https://github.com/temporalio/ui/assets/26808399/85412163-180b-4258-bcf7-2846253115f9">
<img width="1727" alt="image" src="https://github.com/temporalio/ui/assets/26808399/ac7339ff-baab-4227-aaa1-65c80d762b15">

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version: 120.0.6099.199

**Additional context**
The URL of the resulting page is seemingly correct, as it displays the older run id in the form: http://localhost:8080/namespaces/default/workflows/sharedWorkflowId/oldRunId/history

However, the actual page still shows the info of the most recent run, not the run id in the URL.

**Comment by scwhaley** [comment]
@Alex-Tideman Saw you've been active recently, do you have any input on this? My org is looking to integrate Temporal into a large product, and we are debating if this UI is going to be usable for us if we can't see the history of old workflow runs. 

Happy to provide any input or assistance required to better understand if this is a bug or intended behavior!

**Comment by Alex-Tideman** [comment]
Hey @scwhaley,

Could you try updating to +v2.17.3 or latest version? I'm not able to reproduce and you should definitely be able to view old runs. There was a major API change in 2.17.0 that may have caused this in 2.17.0

**Comment by scwhaley** [comment]
Thank @Alex-Tideman for confirming the intended behavior. 

I saw the issue is present on v2.21.0. Upgrading to v.2.22.3 (the UI version used with the latest commit of https://github.com/temporalio/docker-compose) seems to have resolved the issue.

Thanks again, I truly appreciate it!
