### ISSUE TITLE
Error in workflow Event History compact view

### ISSUE THREAD

**Issue by AlexSKuznetsov** [temporalio/ui#1902]
Error in Event History compact view after sending a signal to Workflow.

1. Start workflow
2. Send signal to workflow
3. Open workflow history - compact view

**Screenshots**
![Screenshot 2024-03-08 at 13 52 04](https://github.com/temporalio/ui/assets/47721260/a554b8b6-a37a-4966-b66e-fc0e40b0fd8e)

![Screenshot 2024-03-08 at 12 31 56](https://github.com/temporalio/ui/assets/47721260/f83c1ece-6949-4194-a87c-c81373abff8c)

- OS: MacOS Sonoma Version 14.3.1
- Browser: Version 122.0.6261.94 (Official Build) (arm64)
- TEMPORAL_VERSION=1.22.4
- TEMPORAL_UI_VERSION=2.24.0

**Additional context**

**Comment by Alex-Tideman** [comment]
Fixed
