### ISSUE TITLE
Timezone bug in Timeline view

### ISSUE THREAD

**Issue by harsh-stripe** [temporalio/ui#1964]
**Describe the bug**
When viewing the timeline for a workflow run in temporal-ui, the timeline displays the user's local time as the x-axis labels, even when the UI is configured to display times in UTC.

**To Reproduce**

1. Go to any workflow run
2. Ensure the time setting is set to UTC: 
<img width="105" alt="image" src="https://github.com/temporalio/ui/assets/109252877/e92b1bb6-27dd-47ae-b324-2b6c0b88690f">

3. Scroll down to the timeline view
4. See error where the timeline labels are local time instead of UTC (even though the hover-tooltip displays UTC).

**Expected behavior**
I expect the timeline x-axis labels to be display in UTC instead of local-time.

**Screenshots**
<img width="105" alt="image" src="https://github.com/temporalio/ui/assets/109252877/449ffe7b-a66b-4285-8e03-30d62acc3520">
<img width="493" alt="image" src="https://github.com/temporalio/ui/assets/109252877/653376d9-6087-41b8-b79e-c6293e2631be">
<img width="362" alt="image" src="https://github.com/temporalio/ui/assets/109252877/817677cd-fd4e-4bf8-b326-9ff3b83042b0">

**Desktop (please complete the following information):**

- OS: macOS
- Browser chrome
- Version 2.22.2

**Additional context**
Temporal-ui version: 2.22.2

**Comment by Alex-Tideman** [comment]
Fixed
