### ISSUE TITLE
Can't open workflow details on a workflow that contains special characters

### ISSUE THREAD

**Issue by Semior001** [temporalio/ui#1987]
**Describe the bug**
Opening a workflow with ID like `some.domain.example.simple.ExampleService/ComplexAction(product,query,year:2024 month:4 day:10)` leads to 404.

**To Reproduce**
1. Start any workflow, which has an ID with special characters.
2. Click on it in web UI.

**Expected behavior**
Workflow details are opened.

**Screenshots**
That's what I get now:
![image](https://github.com/temporalio/ui/assets/3617699/b8bc8b38-2313-4047-a3a2-c2bb0bf3766c)
![image](https://github.com/temporalio/ui/assets/3617699/bcc5bc79-1270-41b3-a2a5-ab1a360653d2)

On earlier version (2.21.3) it worked perfectly fine:
![image(38)](https://github.com/temporalio/ui/assets/3617699/981ef6d6-e2c1-49f8-a83b-f3b1146403bf)

**Desktop (please complete the following information):**

- OS: MacOS 14.4.1 
- Browser: Firefox 124.0.2
- Version: temporalio/ui - 2.26.0, temporalio/auto-setup - 1.22.7, temporalio/admin-tools - 1.22.7

**Comment by jontro** [comment]
I think this is the same as https://github.com/temporalio/ui/issues/1084

I added some comments there too recently

**Comment by nikat** [comment]
We're also having this since a recent update, I've tested some names

Workflow IDs that seem to work okay:
```
ExampleWorkflow/1
ExampleWorkflow:1/1
ExampleWorkflow:test-1/1
ExampleWorkflow(1)
ExampleWorkflow(1.0)
```

Workflow IDs that provoke error 404:
```
ExampleWorkflow(1/0)
ExampleWorkflow(1-1)
ExampleWorkflow(1 0)
ExampleWorkflow(1:1)
ExampleWorkflow(1\1)
ExampleWorkflow(1 of 1)
```
