### ISSUE TITLE
Buttons `scrollToTop/Bottom`  overlaps the history timestamp

### ISSUE THREAD

**Issue by trin4ik** [temporalio/ui#2145]
![image](https://github.com/temporalio/ui/assets/839633/57bd2be3-ce49-4fbc-810a-279c65454235)

problem: 
buttons `scrollToTop` and `scrollToBottom` overlaps the history timestamp

solution:
1. hide `scrollToBottom` button on bottom
2. move buttons left, if they overlaps the timestamp

i've prepared a PR, but it does a few things:
1. timestamps hides by computed js `$: showTimestamp = canvasWidth > 1200;`, i think good solutions for this -- use tilewind "responsive design" css like `media` (https://tailwindcss.com/docs/responsive-design)
2. some js to hide `scrollToBottom` if bottom and move `scroll container`, if buttons over history
3. add tooltip `ctrl+up`, `ctrl+down` for scroll buttons. seems, if user need buttons, he not use scroll. it's weird that he doesn't know about keyboard shortcuts and needs buttons.

do i need to split pr into parts or can push one?

**Comment by trin4ik** [comment]
more fast solution -- add `class="opacity-30 hover:opacity-100"` to buttons and no need other steps

**Comment by Alex-Tideman** [comment]
Fixed in https://github.com/temporalio/ui/pull/2269
