### ISSUE TITLE
[Feature Request] Large Workflow IDs may interlap with workflow type

### ISSUE THREAD

**Issue by feedmeapples** [temporalio/ui#215]
### Describe the bug

![image](https://user-images.githubusercontent.com/11838981/148983437-aa2f5125-53d6-4ec5-bc97-886be3f5406a.png)

### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: [e.g. 1.14.0?] and/or SDK version
- Are you using Docker or Kubernetes or building Temporal from source?

**Comment by stevekinney** [comment]
I believe @GiantRobots fixed this. Can you confirm?

**Comment by GiantRobots** [comment]
This was resolved when we added the responsive design.
