### ISSUE TITLE
Please add `Failed` filter on workflow history/compact view

### ISSUE THREAD

**Issue by Portur** [temporalio/ui#2192]
## Is your feature request related to a problem? Please describe.

Not a problem, just a QOL request

## Describe the solution you'd like

Viewing a workflow with hundreds of events/activities overloads the browser. If a filter is added to only view certain activites or even only failed activities it would help to easily investigate the workflow.

## Describe alternatives you've considered

None

## Additional context

None

**Comment by Alex-Tideman** [comment]
Added in https://github.com/temporalio/ui/pull/2269
