### ISSUE TITLE
ui\embed.go pattern all:assets: cannot embed directory assets: contains no embeddable files

### ISSUE THREAD

**Issue by GAVRILOVGLEB** [temporalio/ui#2198]
**Describe the bug**
After git clone have many issues with packages and finally i get an issue with assets into GO file (server/ui/embed.go) in repository haven't got any assets in this folder, please remove this folder from .gitignore

**To Reproduce**

1. pnpm install
2. pnpm dev

**Screenshots**
<img width="563" alt="image" src="https://github.com/temporalio/ui/assets/34240291/562cbc84-5035-4955-b579-72e9ea1345a0">
<img width="398" alt="image" src="https://github.com/temporalio/ui/assets/34240291/e6b5e1b4-cf74-4938-ba91-5f248da7bf5c">

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: chrome

**Comment by Alex-Tideman** [comment]
You need to run `pnpm build:server` after first cloning it
