### ISSUE TITLE
Refresh button for Event history

### ISSUE THREAD

**Issue by artyomabrahamyan** [temporalio/ui#2246]
## Is your feature request related to a problem? Please describe.

Having frequently updating event history, an option to quickly update the screen.

## Describe the solution you'd like

Might be a refresh button in event history page.

## Describe alternatives you've considered

In the previous versions auto-refresh toggle used to be a workaround, but it seems to be removed. Currently refreshing the whole page does the trick.

## Additional context

None.

**Comment by Alex-Tideman** [comment]
This is automatically refreshed when new events come in. We now poll for the history.
