### ISSUE TITLE
Temporal web shows running workflow, when it is actually completed

### ISSUE THREAD

**Issue by mercer** [temporalio/ui#2395]
**Describe the bug**
Sometimes temporal web shows a workflow as running, even if, when I open it, it shows as completed.

**To Reproduce**
Don't know how to reproduce. About 1/100 workflows have this behavior.

**Expected behavior**
A way to mark it as completed, or force ui to sync state.

**Screenshots**
Can't share screenshots, but let me know what i can offer

**Comment by mercer** [comment]
The workaround I found is to manually update the records in executions_visibility from 1 (running) to 2 (completed) for those that are completed.

I'd like to see a fix for this 🙏

**Comment by Alex-Tideman** [comment]
This isn't an issue with the UI, but rather with your visibility store.

**Comment by mercer** [comment]
So where do I report this?

**Comment by alucarddelta** [comment]
We are seeing the same issue with some of our workflows. @mercer Did you ever get around to finding out where to report this?

**Comment by mercer** [comment]
No. Guess there is no support for observability component, at least this is what I take from this.
