### ISSUE TITLE
Env variable for disabling workflow execution stats

### ISSUE THREAD

**Issue by lazy-ninja** [temporalio/ui#2396]
## Is your feature request related to a problem? Please describe.
- When the number of executions goes beyond >1mn. The get workflow counts by statuses API becomes pretty slow and causes an undesirable load on the database (MySQL in my case).

## Describe the solution you'd like
Make the workflow execution count stats optional and provide an option via the env variable to disable it.

## Describe alternatives you've considered
NA

## Additional context
<img width="1209" alt="Screenshot 2024-10-21 at 4 46 57 PM" src="https://github.com/user-attachments/assets/f30470dc-f091-47f0-a62d-0728b250c3eb">

**Comment by Alex-Tideman** [comment]
Hey @lazy-ninja, we've added the TEMPORAL_REFRESH_WORKFLOW_COUNTS_DISABLED env var to allow you to disable the workflow count fetch.

https://github.com/temporalio/ui/blob/7de4ab5989f45a034776e03da267a3ffbe3a90f8/server/docker/config-template.yaml#L21

**Comment by lazy-ninja** [comment]
Thanks @Alex-Tideman, will try it.

**Comment by lazy-ninja** [comment]
@Alex-Tideman, It seems like it disables the refresh but it's fetching the workflow count on the page load and on clicking the refresh button in the UI.
