### ISSUE TITLE
Temporal/UI v2.33.7 release doesn't publish any image

### ISSUE THREAD

**Issue by LauVietVan** [temporalio/ui#2475]
**Describe the bug**
The latest version [v2.33.7](https://github.com/temporalio/ui/releases/tag/v2.33.7) is released without publishing the image to Dockerhub
[v2.33.7](https://github.com/temporalio/ui/releases/tag/v2.33.7)
**To Reproduce**
Release a new version or rerun the failed `Publish Docker` image workflow will not publish any image.

**Expected behavior**

The image `temporalio/ui:v2.33.7` is published to the Dockerhub https://hub.docker.com/r/temporalio/ui.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Alex-Tideman** [comment]
Please see our readme on the Release process:

https://github.com/temporalio/ui-server/releases is where Docker images are released.
