### ISSUE TITLE
[Bug] unable to convert filter expression, invalid StartTime format sent to server

### ISSUE THREAD

**Issue by navaru** [temporalio/ui#249]
### What are you really trying to do?

I am trying to run the temporal UI `temporalio/ui-server` v0.2.0 with `temporalio/temporal` v1.14.4.

### Describe the bug

The default `GET` request `/api/v1/namespaces/default/workflows?query=StartTime+%3E+%222022-01-30T01%3A43%3A45%2B02%3A00%22` returns a 500 error:

```
{
  "code": 2,
  "message": "invalid query: unable to convert filter expression: unable to convert values of comparison expression: StartTime only supports BETWEEN ... AND ... filter",
  "details": [
  ]
}
```

The origin of the error seems to be this commit: https://github.com/temporalio/temporal/commit/1e191789e37069157e204ad3d72db33e4da9fa71

**Comment by skurfuerst** [comment]
Yep, having the same issue and waiting for a fix :)

**Comment by stevekinney** [comment]
#267 should fix this. If it doesn't definitely let me know.
