### ISSUE TITLE
[Feedback] UI/UX

### ISSUE THREAD

**Issue by lorensr** [temporalio/ui#254]
Mix of small visual design stuff and larger things. Happy to go into more detail on anything 🤗

Feels too close to right edge:
![image](https://user-images.githubusercontent.com/251288/152453770-564edf8b-dcfd-4555-879c-788464c8bd16.png)

Vertical center:
![image](https://user-images.githubusercontent.com/251288/152454059-9e0be202-f0a6-442a-aedf-5783ce8d6e47.png)

Would much prefer defaulting to relative or local:
![image](https://user-images.githubusercontent.com/251288/152453857-0a83c726-b457-4e40-bb23-107379ac258a.png)

Small tap target, add padding:

![image](https://user-images.githubusercontent.com/251288/152454000-0056db84-1ba6-47ac-a861-00fb3ac18188.png)

Blue feels funny as focus/active style:
![image](https://user-images.githubusercontent.com/251288/152454187-cb95200d-c492-443c-905d-feb97ba43dc5.png)

Add undo button to toast that appears after clicking Terminate button:

![image](https://user-images.githubusercontent.com/251288/152454584-a4519745-d06e-48e8-a4dc-7d0c81643871.png)

And/or a confirmation dialog—perhaps only on in prod, so it's easier to terminate in development.

Switch time range and status dropdowns so they line up better with relevant columns, like workflow ID and type do:

![image](https://user-images.githubusercontent.com/251288/152454485-6c9e5f0b-d3b8-463f-9476-75d8f693ec08.png)

Current pref is against these colors, feels busy/distracting from the words, but maybe I'll get used to:

![image](https://user-images.githubusercontent.com/251288/152454749-64a8524d-53fe-4271-a8b6-8d6520ba40ec.png)

Also feels busy, maybe no bgcolor for Completed?

![image](https://user-images.githubusercontent.com/251288/152454839-6e815ec0-0b39-468a-8700-cb799b3aaea3.png)

Show labels on hover:

![image](https://user-images.githubusercontent.com/251288/152454939-4372a168-b205-4901-90c2-f5763389c81f.png)

Would much prefer not having this box:

![image](https://user-images.githubusercontent.com/251288/152455213-d7c5e30d-2272-439d-850c-92fd8663617c.png)

would like it to use page scrollbar, not a separate scroll. 

Similarly, don't like the Event History box, and would prefer the right scrollbar as the page scrollbar (still need the separate left one).

Failure spacing to right:

![image](https://user-images.githubusercontent.com/251288/152455679-1e97234f-5beb-49ed-b978-d9d3f04f97c9.png)

**Comment by stevekinney** [comment]
Thanks @lorensr! I'm turning most of these into tasks on the internal product board for the upcoming sprints and then I'll close this meta issue.

Quick question as I recreate and triage: What browser and OS are you using? It looks like macOS and Chrome, but I just wanted to confirm.

**Comment by lorensr** [comment]
Yep!
