### ISSUE TITLE
Better navigation thru workflows/steps using only Keyboard

### ISSUE THREAD

**Issue by kalinicm** [temporalio/ui#264]
**Is your feature request related to a problem? Please describe.**
Navigating thru steps of the workflow requires me to use mouse and click on each step to get data.
Also navigating between workflows and steps is hard with mouse. 
Very very slow. App is blazingly fast.

**Describe the solution you'd like**
When one of the steps is selected, I should be able to move thru them with UP / DOWN cursors on keyboard.
Allow full navigation between workflows listing and entering them, then navigating thru steps in workflow, also make ESCAPE key return to the workflows list.

**Describe alternatives you've considered**
None.

**Additional context**
SvelteKit is heavy on accessbility, this is basic stuff. Using mouse for scanning thru workflows/steps seems like such slow and tiring process. Adding couple of hot-keys would make it perfect.

**Comment by canvanooo** [comment]
@kalinicm Keyboard navigation will be coming as we gear up for GA for the new Web UI. Super passionate about this.
