### ISSUE TITLE
 Navigating to Workflow page fails under non-default namespaces

### ISSUE THREAD

**Issue by feedmeapples** [temporalio/ui#265]
**Describe the bug**

Navigating to a Workflow page fails under non-default namespaces

**To Reproduce**

Register a new namespace
```
tctl --namespace test a namespace register 
```

Start hello-world under `test` namespace

1. Go to http://localhost:3000/namespaces/test/workflows
2. Click on the workflow
4. See 400 error and the URL starting by `http://localhost:3000/namespaces/default/workflows/`

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/11838981/154612612-924e049c-fcb4-4d33-b943-e6dd7ff052d8.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by stevekinney** [comment]
Fixed in #260.
