### ISSUE TITLE
Event history table periodically sets scrollTop to 0

### ISSUE THREAD

**Issue by lorensr** [temporalio/ui#268]
**Describe the bug**

After I scroll down on both sides:
- They both scroll back up
- On the left side, it appears that the first event is selected, but the last event is what's show on the right

https://user-images.githubusercontent.com/251288/155206196-f1ac9c8b-7968-4560-a8ac-6a60060547a2.mp4

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] Is this viewable on the site? I used `docker-compose-ui-experimental.yml`

**Comment by stevekinney** [comment]
I noticed this the other day, it's swapping out DOM nodes when the API refresh is hit.

**Comment by stevekinney** [comment]
This should be solved by #271.
