### ISSUE TITLE
Case-insensitive filtering

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#285]
<img width="1538" alt="Screen Shot 2022-03-07 at 11 51 42 AM" src="https://user-images.githubusercontent.com/119422/157080423-f07e70e7-7156-4394-b4de-f61ec75f88eb.png">

provide ability to do case-insensitive searches for workflow type/id

**Comment by stevekinney** [comment]
We'd need @temporalio/server to support this.
