### ISSUE TITLE
Invalid Workflow Type in history details

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#287]
<img width="988" alt="Screen Shot 2022-03-07 at 11 45 07 AM" src="https://user-images.githubusercontent.com/119422/157080915-da97c3e9-7627-420f-b447-a806b5c3b84f.png">

this is not the workflow type

**Comment by stevekinney** [comment]
These are directly pulled from the API, which means the API is wrong. That said, do you have any suggestions for what you'd like these to be called. We're still going to have to stick to these names in the JSON view, so that could introduce new problems.

**Comment by canvanooo** [comment]
@tsurdilo is that workflow type string in your screenshot not the correct workflow type name?

**Comment by tsurdilo** [comment]
@canvanooo 
in the screenshot, on the right the values are:
Worker Identity
Task Queue Kind

It has nothing to do w/ the Workflow Type

**Comment by tsurdilo** [comment]
I am really sorry to ask, but judging from the questions in this and other open issues, I must ask if people that are working on the new web ui actually use it? I'd be happy to help, maybe we can have a "how to use the old web ui" session maybe that way issues can be analyzed and fixed better/faster?

**Comment by canvanooo** [comment]
@tsurdilo it's difficult for me to tell from a partial screen shot what your workflow type name is or isn't. Really appreciate your help here. It would be helpful to receive more context and what the expected result is for us to shorten troubleshooting cycles.

**Comment by tsurdilo** [comment]
@canvanooo id be happy to jump on slack and talk through all this with you if you think it would be helpful.
