### ISSUE TITLE
Task Queue name incorrect in history details

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#288]
<img width="1536" alt="Screen Shot 2022-03-07 at 11 41 46 AM" src="https://user-images.githubusercontent.com/119422/157080995-355da7d4-db6a-4630-b19e-49ff52e8d87d.png">

this is not the task queue name

**Comment by stevekinney** [comment]
@canvanooo What should we do about this? Right now, we're using the names as they're defined in the API.

**Comment by stevekinney** [comment]
Fixed in #304!
