### ISSUE TITLE
Use of null / unspecified / undefined confusing 

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#289]
<img width="538" alt="Screen Shot 2022-03-07 at 11 59 27 AM" src="https://user-images.githubusercontent.com/119422/157081453-9cfb07c7-69ca-46d9-a5c3-1a0ab99863fa.png">

would be nice to have a single way of describing something thats not defined

**Comment by stevekinney** [comment]
I am not sure that this is a UI issue since this table representation of the API. That said, I am open to suggestions because I don’t disagree.

**Comment by canvanooo** [comment]
@stevekinney we've heard that people would prefer we hide "null" or empty results. That would clean up the noise.
