### ISSUE TITLE
Summary event list is empty

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#290]
<img width="189" alt="Screen Shot 2022-03-07 at 12 06 39 PM" src="https://user-images.githubusercontent.com/119422/157082819-0d6bcd02-9bcf-4c6d-a6ee-a95abc5fb11c.png">

<img width="1533" alt="Screen Shot 2022-03-07 at 12 06 43 PM" src="https://user-images.githubusercontent.com/119422/157082817-782c7595-20ad-4816-83e2-da79c6acb0e1.png">

**Comment by stevekinney** [comment]
Can you provide some context?

**Comment by tsurdilo** [comment]
start workflow, view history, click on that highlighted button in screenshot

**Comment by stevekinney** [comment]
Are they any events in the activities, timers, etc. in the event history? Can you share the full view?

**Comment by stevekinney** [comment]
@canvanooo My gut says we need an empty state for these lists. Should we show the table at all if the collection is empty?

**Comment by canvanooo** [comment]
@tsurdilo is this an example of a workflow that is running and hasn't yet kicked of any activities, timers or signals but will...or this workflow doesn't have activities, timers or signals to populate this view?

**Comment by canvanooo** [comment]
That is the compact view, that would only show activities, signals and timers. It's probable that nothing would show up, so we can include an empty state. Thank you.

**Comment by stevekinney** [comment]
@canvanooo We can probably workshop the copy a bit, but I put this in #301 for now.

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/251000/158283429-858891ae-1d36-42e3-905e-7691f88335b3.png">

**Comment by stevekinney** [comment]
We added an empty state in #301!
