### ISSUE TITLE
[0.4.0] Pending activities

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#305]
If you click on a workflow in the main list view that has pending activities, the history shows first element in history list:

<img width="1372" alt="Screen Shot 2022-03-14 at 9 10 33 PM" src="https://user-images.githubusercontent.com/119422/158286432-21ca42ef-57da-4b7e-81f9-46ad20343191.png">

Maybe it's possible to make this more clear as in what activity is pending and why. Currently the item is not clickable. Would be nice to fix if its possible. ty

**Comment by stevekinney** [comment]
What about something like this? 

<img width="990" alt="image" src="https://user-images.githubusercontent.com/251000/158298255-29d3de54-a832-43e1-a0ac-533b5e65cd0d.png">

I think we're all in agreement that those pending activities shouldn't be in that table. I took them out in #301, but I haven't put them back in anywhere yet.

**Comment by stevekinney** [comment]
This'll ship with #350 and be in the next release.
