### ISSUE TITLE
[0.4.0] Show activity type on associated events

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#306]
In the history view:

<img width="444" alt="Screen Shot 2022-03-14 at 9 17 14 PM" src="https://user-images.githubusercontent.com/119422/158286954-a4423f55-60ac-4998-b19c-be770d988608.png">

Pending activities show "c2" which is my activity type, the associated ActivityTaskScheduleEvent for c2 (latest event in screenshot) does not show the activity type. When you then click on the summary view, you do see the "c2" activity type again:

<img width="1341" alt="Screen Shot 2022-03-14 at 9 17 24 PM" src="https://user-images.githubusercontent.com/119422/158287106-6f334852-b358-4b33-86a9-58e26569a396.png">

Would be nice to have the activity type show in event history (on the left hand side) if possible, if not thats fine too. Ty

**Comment by stevekinney** [comment]
@canvanooo I can do this in a heartbeat if you want to tell me what it should look like. My unsolicited suggestion is we use a heading for the activity name and one of the colorful labels in for the type. I don't even need a design, just tell me what you want it to look like and I can have it ready to go shortly thereafter.
