### ISSUE TITLE
[0.4.0] Allow to sort executions by start time/end time, or a default execution order

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#307]
It seems ( I could be wrong) that the main list view always shows running workflows first, which is really nice, but it would also be useful to show workflows in their "natural" execution order (by start time) and also order by completion time:

<img width="1350" alt="Screen Shot 2022-03-14 at 9 21 29 PM" src="https://user-images.githubusercontent.com/119422/158287480-8c99755e-a550-4bf4-a8ae-1fb428b605ba.png">

**Comment by tsurdilo** [comment]
in comparison, the "old" web ui view for sample workflows looks like this:

<img width="1300" alt="Screen Shot 2022-03-14 at 9 23 35 PM" src="https://user-images.githubusercontent.com/119422/158287582-c33d80ee-5a6b-4926-809a-e12569db9456.png">

**Comment by stevekinney** [comment]
@tsurdilo Are you on MySQL or ElasticSearch? This is known limitation on MySQL with the new unified `ListWorkflows` API that was released in 1.14.

**Comment by tsurdilo** [comment]
@stevekinney i use postgres - https://github.com/tsurdilo/my-temporal-dockercompose/blob/main/docker-compose.yml#L16
Running old and new uis via same docker compose deployment.
Will try to look at code to see what could be the difference.

**Comment by stevekinney** [comment]
@tsurdilo Yea, totally. I think the behavior is the same regardless of which database you’re using that doesn’t support advanced visibility on Temporal server.
