### ISSUE TITLE
[0.4.0] Query link in history view shows 500 page

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#308]
<img width="711" alt="Screen Shot 2022-03-14 at 9 26 25 PM" src="https://user-images.githubusercontent.com/119422/158287795-163b2343-a58f-4ee6-9425-b5c4f37018e8.png">

In this case for a running workflow when clicking on the "Query" link it shows a 500 error page:

<img width="652" alt="Screen Shot 2022-03-14 at 9 27 30 PM" src="https://user-images.githubusercontent.com/119422/158287855-252f205b-0858-4c58-9b3e-76d055ff4fee.png">

**Comment by stevekinney** [comment]
I just recreated this. The "good" news is that it's the same issue as #291 in so far that it's not about the status of the workflow, but whether or not there is a worker available to query.
