### ISSUE TITLE
[0.4.0] Main workflow page missing Workflow Run Id

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#311]
<img width="1341" alt="Screen Shot 2022-03-14 at 9 38 48 PM" src="https://user-images.githubusercontent.com/119422/158288927-d705c56a-d764-46d6-a17d-8822e08fd764.png">

**Comment by tsurdilo** [comment]
In comparison in "old" ui:

<img width="1353" alt="Screen Shot 2022-03-14 at 9 38 41 PM" src="https://user-images.githubusercontent.com/119422/158288949-ceef8e69-7c76-41e6-91a0-262084b512a1.png">

**Comment by tsurdilo** [comment]
it's useful to have run id on the main display as sometimes you just want to take those two and be able to copy/paste them when running tctl commands, or want to paste the workflow id and run id in your code tests.

**Comment by canvanooo** [comment]
Thanks @tsurdilo I want to break this UI out in two views, one that optimizes for local debugging and one that is tuned for cloud operations. I'm going to close this issue for the interim, we've decide to remove run ID for the immediate short-term.

**Comment by tsurdilo** [comment]
Hi @canvanooo 

> we've decide to remove run ID for the immediate short-term

may I please know why? run id is super important info for users
