### ISSUE TITLE
[0.4.0] Failures stack trace is not readable

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#312]
For failed workflows the old ui allows to click on a failure and display the stack trace in a readable way, for example:

<img width="1316" alt="Screen Shot 2022-03-14 at 9 43 59 PM" src="https://user-images.githubusercontent.com/119422/158289378-204e4f5d-e4cd-43d7-b282-df43b0ac5735.png">

The error stack trace in new view is shown js JSON and you cannot really read it as its a 10-mile long string in this display:

<img width="867" alt="Screen Shot 2022-03-14 at 9 42 58 PM" src="https://user-images.githubusercontent.com/119422/158289342-9d259050-b067-4c55-8276-07ceb6667a26.png">

Maybe it will be possible to show the error stack trace in some similar view as before. Thanks.

**Comment by stevekinney** [comment]
@canvanooo If it's a failure, should we just show the stack trace at the top of the view?

**Comment by canvanooo** [comment]
@stevekinney I think so, the failure message goes in the output result, is that current behaviour? Looks like the json format isn't what is preferred and to only show the stackTrace string that's is part of the json, in a prettier format, with an expandable icon to display in a modal.

**Comment by stevekinney** [comment]
@canvanooo Right now, only the completed result goes into result. Do y'all want the failure to go in the result if the workflow has failed?

**Comment by canvanooo** [comment]
@tsurdilo I've moved this over to the UI backlog, and will close this out here.
