### ISSUE TITLE
[0.4.0] Namespace is not "sticky"

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#316]
Change name space to something else than "default", then click on the most top-left temporal icon, 
the view switches back to "default" namespace. 

Would be nice for it to "stick", for example in "old" ui:

<img width="381" alt="Screen Shot 2022-03-14 at 10 13 50 PM" src="https://user-images.githubusercontent.com/119422/158292290-05aaf7ca-955f-41be-a2b1-3b0a2cc25567.png">

**Comment by tsurdilo** [comment]
Reopening because cannot confirm with 0.5.0, see https://github.com/temporalio/ui/issues/358

**Comment by feedmeapples** [comment]
verified it is addressed on v0.7.0

**Comment by feedmeapples** [comment]
closing as verified the fix in v0.9.0
