### ISSUE TITLE
[0.4.0] Advanced Search automatically clears out workflow list

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#319]
<img width="1344" alt="Screen Shot 2022-03-14 at 10 27 46 PM" src="https://user-images.githubusercontent.com/119422/158293781-7d61151d-81d4-4611-babd-af9d25bc7fa7.png">

this is a little bit different then the "old" web ui where when you click on "Advanced Search" it does not clear the list automatically. 
I think it would be useful to not auto-clear list here as well if possible, thanks.

**Comment by stevekinney** [comment]
When I try it in the old UI, it clears out the list and displays an error message, right? (That's still what it's doing under the hood.) We want to work on a parser to validate the input.

@canvanooo Should this even be automatic? Maybe we're better off with a submit button, that way it doesn't clear or error?

**Comment by canvanooo** [comment]
Let's group this into the search epic I'm picking up .. now..

**Comment by canvanooo** [comment]
@stevekinney here is the search button: https://www.figma.com/file/u0hxNQYdSWagO8eOlXkgea/Temporal-Web-UI-v2?node-id=1555%3A26785
