### ISSUE TITLE
[0.4.0] Workflow Terminate is automatic

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#325]
I saw https://github.com/temporalio/ui/pull/130 and thats fine to make reason to terminate optional, but currently there is no "would you really like to terminate" options. Old ui:

<img width="628" alt="Screen Shot 2022-03-14 at 10 47 46 PM" src="https://user-images.githubusercontent.com/119422/158296084-3e0f4baa-7c8f-4d3b-89e6-2ad938083207.png">

Currently as soon as you click terminate you get a green message saying its terminated, w/o any chance to cancel the operation which is permanent. 

Also when you click Terminate the workflow page still shows that workflow as Running - see here:

<img width="1348" alt="Screen Shot 2022-03-14 at 10 48 06 PM" src="https://user-images.githubusercontent.com/119422/158296060-eeae5470-5a69-4ca9-b677-8d2802707c2d.png">

if then you click on Terminate again you get a 404 page:

<img width="1337" alt="Screen Shot 2022-03-14 at 10 50 32 PM" src="https://user-images.githubusercontent.com/119422/158296256-6c861911-5e40-47d2-8ce2-e2d7a3126ff5.png">

You have to refresh the page for the workflow to get "terminated" status and for the Terminate button to dissapear:

<img width="1352" alt="Screen Shot 2022-03-14 at 10 52 14 PM" src="https://user-images.githubusercontent.com/119422/158296404-75a1c181-30bc-4364-82b0-11b29e3d43e2.png">

**Comment by stevekinney** [comment]
@tsurdilo Totally agree. That's been on the to-do list for this sprint and @GiantRobots is going to take care of it today. Stay tuned!

**Comment by tsurdilo** [comment]
Thanks! Just confirming same happens in 0.5.0
