### ISSUE TITLE
[0.4.0] History view workflow description

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#332]
<img width="584" alt="Screen Shot 2022-03-15 at 10 50 41 PM" src="https://user-images.githubusercontent.com/119422/158507186-4a0665ee-9538-446a-b4a0-35d43123ae00.png">

Couple of small changes that imo would help. Not must by any means, feel free to ignore:

1. separate the titles from values with ":" for example "Workflow ID: HelloAsyncActivityWorkflow" 
2. Add started and closed time in this section (its there in old ui)
3. Add the task queue name in this section so its clear on which task queue this workflow is / has executed on 
4. Add State Transitions count which is there in old ui

**Comment by canvanooo** [comment]
@stevekinney  
https://www.figma.com/file/u0hxNQYdSWagO8eOlXkgea/Temporal-Web-UI-v2?node-id=1633%3A21668

**Comment by feedmeapples** [comment]
all of the suggestions are addressed

![image](https://user-images.githubusercontent.com/11838981/161918659-fbfe9a7b-889c-4630-bc01-c1f4612fa697.png)
