### ISSUE TITLE
[0.4.0] Don't display "0s" for timeouts

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#335]
In event history view (when clicking on a particular event and viewing the table with its properties) in 0.4.0 events that are not set for example heartbeatTimeout are shown as "0s". It would be better not show this and leave them blank as its done in v1, for example:

<img width="907" alt="Screen Shot 2022-03-15 at 11 09 00 PM" src="https://user-images.githubusercontent.com/119422/158509162-b42e37d5-ee59-407f-9bbf-98bb86a548d0.png">
<img width="1362" alt="Screen Shot 2022-03-15 at 11 08 51 PM" src="https://user-images.githubusercontent.com/119422/158509163-cea269b0-7e97-47ba-9a49-f4e28b4369b1.png">

**Comment by stevekinney** [comment]
@canvanooo Do you want blank values or just to hide them?
