### ISSUE TITLE
[0.4.0] ActivityTaskSchedule event - namespace is "undefined"

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#336]
<img width="1365" alt="Screen Shot 2022-03-15 at 11 14 44 PM" src="https://user-images.githubusercontent.com/119422/158509680-6d4d64c5-03d1-4a45-a4f5-84ccc1dcfe8b.png">

Namespace here is "undefined", in v1 its blank. I think in both cases we should not display this property at all.

**Comment by stevekinney** [comment]
Yea, I agree, I pulled out all of the `null` and `undefined` values in #329, but I wasn't totally sure what to do with empty strings.

@canvanooo Are you okay with me pulling it out?
