### ISSUE TITLE
[0.4.0] Event Filtering in summary view - Signals

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#342]
Have a workflow that has a bunch of signals:

<img width="581" alt="Screen Shot 2022-03-16 at 11 29 48 AM" src="https://user-images.githubusercontent.com/119422/158627370-cb6bce81-e63b-4f0e-8cbf-37d53f9d1c4e.png">

Then I select "Signal" from the filter dropdown and nothing shows:

<img width="589" alt="Screen Shot 2022-03-16 at 11 29 56 AM" src="https://user-images.githubusercontent.com/119422/158627500-ab61d577-b9ef-45bc-ba3f-9df40a5b43bb.png">

**Comment by stevekinney** [comment]
Fixed in #355!

**Comment by tsurdilo** [comment]
@stevekinney could you set the fix version for these? I am looking at 0.5.0 and this isssue is not fixed, so reopening. Feel free to close if this fix is for 0.6.0 or some future one.

**Comment by tsurdilo** [comment]
Recording (also shows the params not clearing when you filter) [0.5.0]


https://user-images.githubusercontent.com/119422/159080370-143a5c47-5fb5-43da-8424-b691378f6b09.mp4

**Comment by feedmeapples** [comment]
this should be fixed in `v0.6.0`

outgoing signal:
![image](https://user-images.githubusercontent.com/11838981/159083896-5171130a-8100-4a4d-8db2-b6bd5672483f.png)

incoming signal:
![image](https://user-images.githubusercontent.com/11838981/159083939-9e9a07dc-1a4b-49ea-b9a6-4b1fb5936a32.png)

**Comment by tsurdilo** [comment]
@feedmeapples ok thanks. i didnt know which release version to test against as issue was marked as closed
