### ISSUE TITLE
[0.4.0] Summary view table does not adjust to amount of events 

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#346]
1. Look at workflow history view for a workflow with large numbers of events.
2. Click on the 

<img width="264" alt="Screen Shot 2022-03-16 at 11 57 40 AM" src="https://user-images.githubusercontent.com/119422/158632968-cf543c81-5f45-4532-871b-17277cbc22de.png">

button that shows only one or few events
4. The table never adjusts and you get something like this:
<img width="1410" alt="Screen Shot 2022-03-16 at 11 56 01 AM" src="https://user-images.githubusercontent.com/119422/158632890-41dd39a1-f898-4cd6-a61c-dfbcc22a4846.png">

**Comment by stevekinney** [comment]
I am pretty sure this is address in #301 and I will verify today.

**Comment by stevekinney** [comment]
I know that it's solved in #350, so I am just going to tie it to that one.

**Comment by tsurdilo** [comment]
I can confirm this is fixed in 0.5.0. thanks!
