### ISSUE TITLE
[0.4.0] Large JSON history view - add "back to top" button

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#347]
When viewing large event histories as JSON format once you scroll all the way down there is no easy way to go back to top, 
recording of experience:

https://user-images.githubusercontent.com/119422/158635356-3a088275-b35c-4abc-b944-92c2828cc778.mp4

v1 does not have this issue as the top part of the page at least is always there that allows me to switch back to different view or select different namespace regardless where in history i am looking at:

<img width="1531" alt="Screen Shot 2022-03-16 at 12 34 01 PM" src="https://user-images.githubusercontent.com/119422/158640760-438f4533-bac3-496b-ba32-89edab79a10d.png">

One more super minor thing, and its probably just me, it's hard for me to read that json on black background. It's super nice that the json itself is color-coded but its easier to just read it in the v1 color scheme (black text on white background). Maybe there is a way to adjust the colors to help people with different preferences.

**Comment by stevekinney** [comment]
@canvanooo Feel free to kick the ball back to me when this is ready for engineering work.

**Comment by canvanooo** [comment]
@tsurdilo I've move these requests to the UI backlog and will close the issue here.
