### ISSUE TITLE
[0.5.0] Multiple namespaces not working correctly

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#358]
In 0.5.0 its not possible to have multiple namespaces at all. The dropdown only shows default and thats it

**Comment by tsurdilo** [comment]
Recording


https://user-images.githubusercontent.com/119422/159081856-a2a5201a-b79a-4aa7-b5df-5e514e11e442.mp4

**Comment by feedmeapples** [comment]
should be fixed in `v0.6.0` https://github.com/temporalio/ui/pull/361
