### ISSUE TITLE
[0.7.1] Query page is not returning query data, but instead an empty JSON object

### ISSUE THREAD

**Issue by mastermanu** [temporalio/ui#374]
**Describe the bug**
Try and run a query against a WF that has a registered query handler.

![image](https://user-images.githubusercontent.com/5552381/159825487-08e439d4-60f9-4dc4-9691-9547b7cae9f5.png)

**Comment by feedmeapples** [comment]
should be fixed in v0.8.0 with https://github.com/temporalio/ui/pull/384
