### ISSUE TITLE
[0.7.1] Don't show archival page if the cluster doesn't support archival

### ISSUE THREAD

**Issue by mastermanu** [temporalio/ui#378]
![image](https://user-images.githubusercontent.com/5552381/159826058-9c4fe43f-7475-43ca-8798-f2ab68940ebc.png)

**Comment by stevekinney** [comment]
@GiantRobots Can you add an `isCloud` check here?

**Comment by GiantRobots** [comment]
https://github.com/temporalio/ui/commit/1b3a84ed79c2d612f572aaeeaeefce7f260b5e52
Resolved
