### ISSUE TITLE
[0.7.1] State Transition and Event Count is missing from the Workflow Summary Page

### ISSUE THREAD

**Issue by mastermanu** [temporalio/ui#379]

**Comment by stevekinney** [comment]
@canvanooo Do you have these in a design somewhere? We can add them in super quick.

**Comment by canvanooo** [comment]
Yes & shared w the team.

**Comment by feedmeapples** [comment]
confirming:
![image](https://user-images.githubusercontent.com/11838981/161912525-bbd37d4c-f9be-4204-bee4-bfc4da08208b.png)
