### ISSUE TITLE
Build Toggle Buttons Using Context

### ISSUE THREAD

**Issue by GiantRobots** [temporalio/ui#389]
https://github.com/temporalio/ui/pull/386/files#diff-0295f0c4f0906fa6d930b90860693f9d7c3f68eeb98f3de445d534de7b56e07bR63-R84

So we can avoid code like that lets build a Toggle Button Component/Tab Component that uses context to pass state to the children and allows just a name instead of re-making the tab every time.

**Comment by Alex-Tideman** [comment]
Refactored to use routes for the toggle buttons in the importer. I think some day we will want this, but our current strategy is to use route changes on toggle button clicks instead of UI state.
