### ISSUE TITLE
CountWorkflow calls from the Temporal UI

### ISSUE THREAD

**Issue by jPomeranz** [temporalio/ui#402]
**Is your feature request related to a problem? Please describe.**
We often want to quickly know how many open workflow executions we have for operational reasons.

**Describe the solution you'd like**
We'd like to be able to execute CountWorkflow API calls directly from the UI. Support for running a more advanced query would be great so we can filter out long-running workflows that we expect to persist around, but isn't necessary for an initial prototype.

**Describe alternatives you've considered**
We could use the SDK or TCTL instead, but it is problematic for our company's usage since we aren't allowed to directly interface with these from dev machines due to security restrictions, so we would have to do some extra work to build a maintain a solution.

**Additional context**

**Comment by feedmeapples** [comment]
API is available http://localhost:8080/openapi/#/WorkflowService/WorkflowService_CountWorkflowExecutions

This API depends on Elastic Search being enabled though, so this won't work if ES is disabled. It is also not known in advance whether ES is enabled, though the server team might add this `ES enabled` state as part of cluster or other responses. If not added, we can react based on the error coming from the CountWorkflowExecutions API
