### ISSUE TITLE
[0.9.0] Default to relative time, remember settings

### ISSUE THREAD

**Issue by jmcnevin** [temporalio/ui#424]
**Is your feature request related to a problem? Please describe.**
By default, all workflow timestamps are shown in UTC, but it would be far more useful to show them in relative or local time for most users.  In addition, if someone chooses to change the timestamp display method from the default, it would be nice if the UI remembered that preference.

**Describe the solution you'd like**
Change the default timestamp display from UTC to something else, and remember the preference.

**Comment by canvanooo** [comment]
Hi @jmcnevin thanks for posting this, we definitely have persistence on our near-term roadmap. If I could ask you a question, would you like this date & time setting to carry over to the workflow details page by default, or would you like a separate persistent setting for workflow details?
