### ISSUE TITLE
[0.9.0] Allow disabling write operations

### ISSUE THREAD

**Issue by jmcnevin** [temporalio/ui#425]
**Is your feature request related to a problem? Please describe.**
There doesn't seem to currently be a way to prevent operations like "terminate workflow" in the config.  Would like to see this functionality in the new UI.

**Describe the solution you'd like**
Add the ability to disable write operations in the server config.

**Comment by canvanooo** [comment]
Hi @jmcnevin thank you for this feedback. Are you specifically looking to disable these capabilities or map them to different role/permissions?

**Comment by jmcnevin** [comment]
The old UI had the ability to disable all write operations in the config file, but I'd be open to any solution, really.

**Comment by stevekinney** [comment]
Right on. This is easy enough to do on the client-side. @feedmeapples Can you do a spike on _also_ disabling this in temporalio/ui-server#135?

**Comment by feedmeapples** [comment]
we can add a whitelist of read APIs ui-server side, allow Reads and manually decline the rest

**Comment by feedmeapples** [comment]
addressed with the sort button 
![image](https://user-images.githubusercontent.com/11838981/164044742-c030b758-ca1e-4ecb-954e-37ad330892f4.png)

**Comment by drewhoskins-stripe** [comment]
We'd like to be able to disable writes as well.  Ideally, we'd be able to provide a link from the terminate button to our own web address.

**Comment by sstarcher** [comment]
This would be helpful to have two classes of users.  Where one set of users only have read only access.

**Comment by stevekinney** [comment]
I _believe_ this has been implemented, but we'll do an audit if there are new features that need additional gating.

**Comment by royreznik** [comment]
Hello, @stevekinney Is there a docs about it somewhere?

**Comment by pritam-ajmire** [comment]
We are using self hosted temporal, We need to implement the role based access for temporal UI, if you have any docs related to the same can you share it.
