### ISSUE TITLE
[0.10.1] Header is shown twice on Login screen 

### ISSUE THREAD

**Issue by feedmeapples** [temporalio/ui#431]
**Describe the bug**

Header is shown twice on Login screen 

**To Reproduce**

1. Start the UI
2. Go to http://localhost:8080/login

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/11838981/163274259-51fa5861-0447-4e36-b2f4-5a45aeb9589e.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by Alex-Tideman** [comment]
Fixed in v0.10.2
