### ISSUE TITLE
Use History.pushState

### ISSUE THREAD

**Issue by lorensr** [temporalio/ui#434]
**Is your feature request related to a problem? Please describe.**

When I hit the browser back button, I go back to the Chrome new tab screen.

**Describe the solution you'd like**

I'd like to go to the previous path/route.

**Comment by canvanooo** [comment]
Thanks @lorensr we're already on it and the fix should be in the next release :)

**Comment by Alex-Tideman** [comment]
Hey @lorensr this should be fixed now in the latest release if you would like to retest. Thanks!

**Comment by lorensr** [comment]
Works! One thing: after hitting `<`, I expected to be able to go forward in history, but I wasn't able to.

![image](https://user-images.githubusercontent.com/251288/164060199-58f2eaa6-9160-4b73-8880-1b59086eb309.png)
