### ISSUE TITLE
[0.10.1] 404 error after logging in

### ISSUE THREAD

**Issue by jmcnevin** [temporalio/ui#437]
**Describe the bug**
We are seeing the attached screen after logging in with SSO.  The path being requested is `﻿/namespaces/undefined/workflows?time-range=24+hours`.  Also, the namespaces dropdown is empty.

**Screenshots**
<img width="1386" alt="Screen Shot 2022-04-14 at 10 12 46 AM" src="https://user-images.githubusercontent.com/12859/163420725-ae65b8ad-af91-47af-bc7d-cbbf551a5500.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Firefox

**Comment by Alex-Tideman** [comment]
Thanks @jmcnevin for the report, this will be fixed in v0.10.2.

**Comment by jmcnevin** [comment]
This appears to still be happening in 0.10.2.

**Comment by Alex-Tideman** [comment]
Can you give this another shot @jmcnevin on 0.10.3? If it's still an issue I'll dig into it. Thanks!

**Comment by jmcnevin** [comment]
Yeah, still having problems in 0.10.3.  Now we're actually seeing a rapid redirect loop between the login page and the workflows list page.

**Comment by Alex-Tideman** [comment]
Thanks, we identified the issue with the redirect and have a fix in a new release that will come out today or tomorrow morning.

**Comment by jmcnevin** [comment]
Tried again with 0.11.0 this morning.  I still seem to be in a login loop that never gets me to the workflows list page.
