### ISSUE TITLE
[Bug] Wrong tctl commands provided for enabling archival

### ISSUE THREAD

**Issue by sahilvv** [temporalio/ui#455]
### What are you really trying to do?

Clicked on archival tab for a given namespace

### Describe the bug

tctl instructions reference the "default" namespace vs the namespace currently the user is interested. 

![Screen Shot 2022-04-18 at 3 18 20 PM](https://user-images.githubusercontent.com/7732609/163886669-f3b38158-8da0-45cd-a7e0-78ca7e11a150.png)

### Minimal Reproduction

Create a namespace "scratchpad" and try to navigate to archival tab.

### Environment/Versions

ui-server: 0.9

**Comment by stevekinney** [comment]
Thanks! I'm going to merge #454 and that should address the issue!

**Comment by feedmeapples** [comment]
ty
