### ISSUE TITLE
[0.10.6] Enable archival - 400 page

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#485]
Enable archival:

     tctl --namespace default namespace update --has enabled
     tctl --namespace default namespace update -vas enabled

Click "Archival" link, page shows 400 error:

<img width="1612" alt="Screen Shot 2022-04-25 at 11 54 13 PM" src="https://user-images.githubusercontent.com/119422/165217891-49e4500a-b8d6-4e07-9d50-325d84fa39a1.png">

**Comment by Alex-Tideman** [comment]
@tsurdilo could you try again in v0.11.0? Thanks!
