### ISSUE TITLE
"Recent Events" numbering is obscured.

### ISSUE THREAD

**Issue by krousey** [temporalio/ui#496]
**Describe the bug**
When viewing the history of a workflow, the numbering of the "Recent Events" starts to overlap with the event type when reaching the triple digits.

**To Reproduce**

1. Find a workflow with hundreds of events.
2. Go to 'History'
3. Scroll down to 'Recent events'
4. Look at any event with a triple digit number and how it overlaps with the event type.

**Expected behavior**
I expect to be able to clearly read the number.

**Screenshots**
<img width="399" alt="Screen Shot 2022-04-28 at 11 42 48 AM" src="https://user-images.githubusercontent.com/157083/165824724-e29470cd-094c-4e0d-a9d3-52ac09d33c6d.png">

**Desktop (please complete the following information):**

- OS: macOS Monteray Version 12.3.1
- Browser: Chrome
- Version 100.0.4896.127 (Official Build) (x86_64)

**Comment by Alex-Tideman** [comment]
Thanks @krousey! Already has been fixed and will be in v0.12.0 release.
