### ISSUE TITLE
Allow disabling New Version info banner

### ISSUE THREAD

**Issue by sahilvv** [temporalio/ui#501]
**Describe the bug**
0.12 release of ui-server brought in feature to display a banner at top by parsing the github releases page. However, contacting public github.com is restricted from our company production environment. 

**To Reproduce**
Deploy 0.12 version after 0.12.1 or higher version is available and observe this behavior.

**Expected behavior**
Provide a config switch to turn off this feature. 

**Screenshots**
N/A

**Desktop (please complete the following information):**

- Version - 0.12

**Additional context**

**Comment by feedmeapples** [comment]
resolving with #524
