### ISSUE TITLE
[0.12.1] Support raw histories in the UI

### ISSUE THREAD

**Issue by feedmeapples** [temporalio/ui#504]
**Describe the bug**

Temporal Service has a configuration option to send raw history to improve performance. In this case a call to `GetWorkflowExecutionHistory` is going to return
```
{
  "history": {
    "events": [
      // EMPTY
    ]
  },
  "rawHistory": [
      // NOT EMPTY
  ],
  "nextPageToken": null,
  "archived": false
}
```

In such cases the UI is going to show empty History Events

**To Reproduce**

1. When starting Temporal Service, set a dynamic config variable `frontend.sendRawWorkflowHistory` to true. https://github.com/temporalio/temporal/tree/master/config/dynamicconfig
2. Start Temporal Service
3. Run any workflow and go to the History view on the UI
4. See that the events list is empty

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

https://community.temporal.io/t/web-ui-with-elasticsearch-no-history-and-stacktrace/4332/25?u=ruslan

**Comment by stevekinney** [comment]
Verified that this _and_ #569 have been addressed.
