### ISSUE TITLE
Please show both workflow id and run id on the main page

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#533]
Note, hiding some info cause this screenshot is from an user/customer.
<img width="1236" alt="Screen Shot 2022-05-13 at 8 43 53 PM" src="https://user-images.githubusercontent.com/119422/168404390-135c99d1-ed85-41ae-95f4-7d3f99d6fd99.png">

Here we have a bunch of failed workflows with the same workflow id and same workflow type. 
There is no easy way to find the one with a specific run id since it's not displayed. 
Users have to either click on each one and then look for the run id or run a search query to find it. 
Would be really nice if the workflow run id was also displayed in this table. 

Thanks.

**Comment by canvanooo** [comment]
Thanks @tsurdilo This highlights that we need to improve the information architecture for workflows with the same ID and type.

**Comment by Alex-Tideman** [comment]
Run Id has been added to table
