### ISSUE TITLE
Web Ui not showing workflows when Days dropdown is changed

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#535]
This is an issue that affects our customers currently. Ping me for more info I can share a video that shows the reproduce.

If you have workflows that are 5 days old, the main page does not show them (dropdown defaults to 1 days).
However once you switch to 7 days, the workflows still do not show, you have to refresh the page for them to show.

**Comment by stevekinney** [comment]
This should be fixed in #538!
