### ISSUE TITLE
Running workflow when worker is down - error displayed

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#562]
<img width="1635" alt="Screen Shot 2022-06-01 at 12 34 18 PM" src="https://user-images.githubusercontent.com/119422/171455344-69f48e7b-10b6-487e-a5dc-770da6e696a0.png">

To reproduce, start a workflow exec and shut down your workers. 
I am not sure why this error is displayed, seems no info is really missing.

**Comment by Alex-Tideman** [comment]
@tsurdilo We show this error because it's a running workflow but it has no running workers. Would you not want to see this in that situation or would like to see different copy? @canvanooo

**Comment by lorensr** [comment]
Here's a suggestion: #604

**Comment by stevekinney** [comment]
Closing in favor of #604.
