### ISSUE TITLE
Per page dropbox glitched

### ISSUE THREAD

**Issue by gabrielsantosblanchet** [temporalio/ui#564]
**Describe the bug**
on the workflow tab when you select the per page option from 100 to 500 it start switching between the 2 values

**To Reproduce**

1. Go to 'workflows tab'
2. Click on 'per page from 100 to 500' or 'per page from 500 to 100' 

**Expected behavior**
change amount of entries to the specified value

**Screenshots**
![chrome-capture-2022-5-1](https://user-images.githubusercontent.com/71042624/171491946-653feadf-4c18-4971-9b2e-09901f839821.gif)

**Desktop (please complete the following information):**

- OS: windows 10 64 buit 
- Browser chrome 102.0.5005.63 (64)bit
- Version latest as of June 1st 2022 

**Additional context**
don't know if it matter but I have a cloud based temporal cluster(aws) and im running the ui locally with docker

**Comment by stevekinney** [comment]
@gabrielsantosblanchet Thanks for the bug report?

@Alex-Tideman, you fixed this in #566, right?
