### ISSUE TITLE
Support serving UI under subpaths

### ISSUE THREAD

**Issue by feedmeapples** [temporalio/ui#576]
**Is your feature request related to a problem? Please describe.**

Users host multiple apps under the same domain and different URL sub-paths. Web UI currently can be served only under a root path which can be a blocker for running it

**Describe the solution you'd like**

Support serving UI under custom paths, ex [mydomain.com/temporal/ui/](http://mydomain.com/temporal/ui/) instead of just the root [mydomain.com/](http://mydomain.com/) 

**Additional context**

Web UI v1 exposes an env variable `TEMPORAL_WEB_ROOT_PATH` to support this, though it also required users to build Web UI themselves. Ideally find a way to not have to rebuild and only require a config option

**Comment by krn0x2** [comment]
Hi, Path based routing support is  a much awaited feature for us too! Would save us form having to regenerate our SSL certificate with a new subdomain just for serving temporal UI.  Is there any tentative timeline for this change?

**Comment by lmbai** [comment]
same here ..

**Comment by feedmeapples** [comment]
thx for the upvotes. Working on this as a Spike task ideally to find a way to support this w/o rebuilding the UI. Will keep you posted

**Comment by vinodnaidu02** [comment]
Is there any ETA for this fix? Any workaround which can be done now to use a custom path?

**Comment by feedmeapples** [comment]
@vinodnaidu02 currently in progress though no ETA, sent a draft PR ^

**Comment by vinodnaidu02** [comment]
> @vinodnaidu02 sent a draft PR ^, should be available with the next release. Seems will require rebuilding the docker image with an env variable

Hey thank you for the fix, I tried this PR in my local and tried to run locally with a custom path defined in publicPath. Still, I am getting 404 for the custom path URL. Am I missing something?

**Comment by feedmeapples** [comment]
> > @vinodnaidu02 sent a draft PR ^, should be available with the next release. Seems will require rebuilding the docker image with an env variable
> 
> Hey thank you for the fix, I tried this PR in my local and tried to run locally with a custom path defined in publicPath. Still, I am getting 404 for the custom path URL. Am I missing something?

it's just a draft, also requires ui side changes. I'm setting it to ready for review once it fully works

**Comment by feedmeapples** [comment]
both ui-server and ui PRs are now ready for review

**Comment by feedmeapples** [comment]
have run into more issues when serving the UI from UI-Server. Now it's fixed and ready

**Comment by feedmeapples** [comment]
if this is implemented we should be able to support Public Paths w/o rebuilding the docker image https://github.com/sveltejs/kit/issues/595

**Comment by feedmeapples** [comment]
Reopened this issue as it works on v2.6.0 only

v2.6.1 introduces a regression to the feature https://github.com/temporalio/ui-server/releases/tag/v2.6.1

**Comment by diddowill** [comment]
@feedmeapples 
Is there a summary of this work?

- Which version shall we use? 2.6.0 or 2.8.0?
- Does the image build is still requred? 
If yes then I think we should continue to work on it to solve the [original problem](https://github.com/temporalio/web/issues/473):
_It is quite cumbersome to build your own image unlike the official image.
Having it in the Dockerfile loses the effectiveness of it in the first place. We need the ability to set it during the deployment._

**Comment by feedmeapples** [comment]
> 

If this is still relevant, Public Path is supported again starting v2.8.0 https://github.com/temporalio/ui-server/releases/tag/v2.8.0

The build is required as the UI static files (js, html css) need to be re-built with the correct paths. Some notes on how to build & run https://github.com/temporalio/ui-server/tree/main/docker#serve-ui-under-a-sub-path (should appear in the official docs soon)
