### ISSUE TITLE
Event filter dropdown does not include marker recorded events

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#584]
<img width="1330" alt="Screen Shot 2022-06-13 at 9 49 01 AM" src="https://user-images.githubusercontent.com/119422/173368424-833829bd-7f36-4599-9bc2-41c26015a9d6.png">

Same with v1:

<img width="630" alt="Screen Shot 2022-06-13 at 9 50 15 AM" src="https://user-images.githubusercontent.com/119422/173368565-40db6620-ee3c-4392-907d-bcde00ff9ba3.png">

Dropdown should also include marker recorded events so users can easier see all their local activity invocations.

Related forum post: https://community.temporal.io/t/marker-recorded-not-contained-in-the-ui-hard-to-find-my-local-activities/4951

**Comment by stevekinney** [comment]
I believe this is fixed in Web v2.

<img width="943" alt="image" src="https://user-images.githubusercontent.com/251000/178287802-6861fc97-251a-4d6e-8374-7c1a864890ee.png">
