### ISSUE TITLE
Inputs / results don't match workflow execution

### ISSUE THREAD

**Issue by danielpeach** [temporalio/ui#586]
**Describe the bug**

I see inputs / results that don't match my workflow execution.

**To Reproduce**

1. Load workflow
2. Observe inputs / results
3. Load a different workflow
4. Observe inputs / results -> same inputs / results as step 2. 

**Expected behavior**

I expect to see the inputs / results that correspond to my workflow.

**Screenshots**

Notice same run ID in screenshot below but different inputs / results:

![Screen Shot 2022-06-14 at 10 45 53 AM](https://user-images.githubusercontent.com/13868700/173608013-339a3a4d-72c1-45d4-87bd-c43b0b2517b6.png)

![Screen Shot 2022-06-14 at 10 46 29 AM](https://user-images.githubusercontent.com/13868700/173608269-01275870-567a-4f28-a882-4398bafc6bf8.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] iOS
- Browser [e.g. chrome, safari] chrome
- Version [e.g. 22] 102.0.5005.61

**Additional context**

**Comment by Alex-Tideman** [comment]
@danielpeach This has been fixed in 2.0.0 release
