### ISSUE TITLE
Console error on load

### ISSUE THREAD

**Issue by lorensr** [temporalio/ui#603]
**Describe the bug**

![image](https://user-images.githubusercontent.com/251288/174416260-04c471f1-ca71-4a38-b720-f0ee77d93eb3.png)

![image](https://user-images.githubusercontent.com/251288/174416263-31729f07-d005-4565-861d-7da8db0581ab.png)

**To Reproduce**

Load https://web.loren.temporal-dev.tmprl.cloud/

**Desktop (please complete the following information):**

- Browser latest mac chrome

**Comment by stevekinney** [comment]
It looks like this has been fixed. I can't reproduce it.
