### ISSUE TITLE
Improve stack trace message when no workers are running

### ISSUE THREAD

**Issue by lorensr** [temporalio/ui#605]
**Is your feature request related to a problem? Please describe.**

This takes so long that I didn't actually believe there was still a request in flight 😄

<img width="733" alt="image" src="https://user-images.githubusercontent.com/251288/174416672-763d93d0-1116-4970-9a8c-5586e9c71845.png">

**Describe the solution you'd like**

- Add a loading animation and a shorter timeout. 
- If the shorter timeout fires, or if you get this response:

<img width="385" alt="image" src="https://user-images.githubusercontent.com/251288/174418245-a68fdce1-fff5-4269-9e6b-8c77db7b534e.png">

Then, instead of "an error occurred":

<img width="586" alt="image" src="https://user-images.githubusercontent.com/251288/174418334-3d96ed36-cfba-4fa6-80ec-556197717368.png">

Display:

```
[Stack trace Query](https://docs.temporal.io/concepts/what-is-a-query/#stack-trace-query) timed out

This usually means there are no Workers connected to the `my-queue` Task Queue.
```

**Comment by yiminc** [comment]
Maybe a link to go to task queue view to verify if there is worker connected or not.

**Comment by lorensr** [comment]
Oh yeah, when we already know `Workers: 0`, we can skip the request and display:

```
To enable [stack traces](https://docs.temporal.io/concepts/what-is-a-query/#stack-trace-query), run a Worker on the `my-queue` Task Queue.
```

<img width="151" alt="image" src="https://user-images.githubusercontent.com/251288/174420204-1964c3f8-f74d-40c2-af0b-a03b9aced935.png">

**Comment by stevekinney** [comment]
I'm into it. I'm just going to ping @canvanooo for visibility, but my take is that this is totally both reasonable and doable.

**Comment by Alex-Tideman** [comment]
-
