### ISSUE TITLE
Explain Data Encoder

### ISSUE THREAD

**Issue by lorensr** [temporalio/ui#606]
**Is your feature request related to a problem? Please describe.**

I don't know what this is/does:

![image](https://user-images.githubusercontent.com/251288/174418617-0d1112b7-873c-489e-bad8-37a7fdb53d91.png)

When I click, nothing happens.

**Describe the solution you'd like**

- `cursor: pointer`
- Tool tip on hover
- Make something happen when I click it

**Comment by flossypurse** [comment]
Is this going to be the new view?
Will there be a modal or a screen for the Data Encoder inputs?

Any other context?

**Comment by lorensr** [comment]
Now the text has cursor pointer and highlights, but the tooltip only shows up when hovering over icon, not text.

<img width="187" alt="image" src="https://user-images.githubusercontent.com/251288/198751933-404a7355-8883-4bfc-b437-8405766182d0.png">

**Comment by Alex-Tideman** [comment]
Codec Server has more details and info in the new Codec Server header
