### ISSUE TITLE
Compact view is empty

### ISSUE THREAD

**Issue by lorensr** [temporalio/ui#619]
**Describe the bug**

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/251288/175165694-6eec1b03-20ea-4d13-8e61-39c5c264c203.png">

**Expected behavior**

It should have events like the Timeline view has:

<img width="995" alt="image" src="https://user-images.githubusercontent.com/251288/175165976-f097ca28-3da4-4cc7-8cc2-d34bd8c9859d.png">

or better explain why it doesn't have events. From the error message, I don't know what the current filter is or how to change it.

**Comment by Alex-Tideman** [comment]
@lorensr Thanks Loren! FYI we currently don't group every event (i.e. we programmatically check for certain events to start the creation of a group) for the compact view. I.e. there are some event histories that won't show anything in the compact view. Would love to keep build them out, what would you like to to see here for the grouping(s)? 

[Link to group code](https://github.com/temporalio/ui/blob/main/src/lib/models/event-groups/create-event-group.ts#L73-L88)

**Comment by lorensr** [comment]
Not sure, will keep that in mind, thanks. In meantime, this issue can just be about the empty state message: 

> or better explain why it doesn't have events. From the error message, I don't know what the current filter is or how to change it.

I guess the simplest thing to do is replace the empty message with:

Compact view groups together these events:

- Activity
- Timer
- Signal Received
- Signal Sent
- Child Workflow
- Marker

There are no such events in this Workflow's Event History.

**Comment by stevekinney** [comment]
Since this is the intended behavior for now, I'm going to reclassify this as an enhancement.
