### ISSUE TITLE
Workflow Advance Search - searching multiple times

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#622]
Opening issue on behalf of user, forum post: https://community.temporal.io/t/temporal-ui-workflows-advanced-search/5044

version: 2.0.0

**Comment by stevekinney** [comment]
**Quick note**: My initial suspicion triaging this bug is that is related to differences in the behavior of [Standard and Advanced Visibility](https://docs.temporal.io/visibility/). I looped in @yiminc and @Alex-Tideman to work on short term fixes and long-term solutions to this.
