### ISSUE TITLE
v2 of ui dropped trace view

### ISSUE THREAD

**Issue by jdupl123** [temporalio/ui#654]
**Is your feature request related to a problem? Please describe.**
Version 1 of the ui had a handy trace of activities running 
<img width="992" alt="image" src="https://user-images.githubusercontent.com/4902386/176819497-ce4490ad-1ef7-4361-96f3-ce29d1e26812.png">
I am frustrated that it is no longer available.

**Describe the solution you'd like**
I would like something similar or better for v2

**Describe alternatives you've considered**
we could use Jager for this but it was kinda nice to have a first level view in temporal.

**Comment by stevekinney** [comment]
This is totally on the roadmap. We’re just looking into ways to make this scalable for large event histories.
