### ISSUE TITLE
UI Filters not updating properly

### ISSUE THREAD

**Issue by situ25** [temporalio/ui#655]
All the filters of the new UI Update only **every second time**.

**To Reproduce**
1)Run temporal server and UI-server separately. 
2)Run UI separately.
3)Change the Workflow status filter to "Terminated" to display only terminated workflows.( This would change the URL but it will keep displaying previous content.)
4)Choose something else from that filter.(It will work second time)
 
**Expected behavior**
1)Filters should work every time.

This function is only getting called **every second time** the filter is changed.
```
const updateWorkflows: StartStopNotifier<WorkflowExecution[]> = (set) => {
  return parameters.subscribe(({ namespace, query }) => {
    withLoading(loading, updating, async () => {
      const { workflows } = await fetchAllWorkflows(namespace, { query });
      set(workflows);
    });
  });
};
```

**Screenshots**
Raised it here before
https://community.temporal.io/t/filters-in-ui-beta-not-working/5126

**Desktop**
- OS: windows
- Browser:-  Chrome and Firefox

**Comment by stevekinney** [comment]
Thanks for the report. I'm looking into this, but I'm [having a hard time recreating the issue](https://user-images.githubusercontent.com/251000/176910180-dd329bc1-d08a-427f-92ec-36a041eb4539.mov).

**Comment by situ25** [comment]
> Thanks for the report. I'm looking into this, but I'm [having a hard time recreating the issue](https://user-images.githubusercontent.com/251000/176910180-dd329bc1-d08a-427f-92ec-36a041eb4539.mov).

Thanks for looking into this. Could you point out at which step you are finding it hard to recreate.
