### ISSUE TITLE
Allow navigation to child workflows

### ISSUE THREAD

**Issue by lorensr** [temporalio/ui#672]
**Is your feature request related to a problem? Please describe.**

It's easy to navigate to a parent from a child:

<img width="520" alt="image" src="https://user-images.githubusercontent.com/251288/177663957-2e55fc5d-5695-4021-8591-ce17ec6cbf20.png">

**Describe the solution you'd like**

It would be nice if there was a list links to children at the top, and links in the individual StartChild events.

**Comment by stevekinney** [comment]
Do you know if we get this in `DescribeWorkflowExecution` anywhere?

**Comment by lorensr** [comment]
Not all children, just pending:

https://github.com/temporalio/api/blob/a3effacd3c06e0b79f8543d3c4bbf3623c48380f/temporal/api/workflowservice/v1/request_response.proto#L743

`PendingChildExecutionInfo`: https://github.com/temporalio/api/blob/a3effacd3c06e0b79f8543d3c4bbf3623c48380f/temporal/api/workflow/v1/message.proto#L83-L90
