### ISSUE TITLE
Compact view order by `Date & Time`

### ISSUE THREAD

**Issue by afitz0** [temporalio/ui#784]
**Is your feature request related to a problem? Please describe.**
In the default state, the `History` and `Compact` views have opposite orders. The main/full History is ordered most-recent-on-top, Compact is opposite. In Compact view, this ordering is fixed.

**Describe the solution you'd like**
I would want the ordering to be the same between the two views and modify-able by users in either one.

**Describe alternatives you've considered**
In the Compact view, I could see it being necessary to disable the "Show Elapsed Time" option to avoid complications in its calculation with the groupings.

**Comment by stevekinney** [comment]
This might a _little_ tricky since we can’t query event histories and doing it memory might break at scale. But, I’m going to keep this open since we can and should do a research spike at least.
