### ISSUE TITLE
Ability to sort "Recent Workflows" by start/end time by clicking on column headers. 

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#791]
**Is your feature request related to a problem? Please describe.**
Would be nice to have ability sort displayed workflows in "Recent Workflows" view by clicking on the Start / End table headers.

Community slack request: https://temporalio.slack.com/archives/C011AAP3GFP/p1661487970237259

**Comment by MattGurney** [comment]
My problem is I want to see the latest workflow executions across all types of workflow within a namespace ordered by execution time.

**Comment by chanjoongkim** [comment]
We recently ran into an issue where we needed to see the oldest Running workflows from the UI, however we were not able to easily sort the workflows by start time and would be interested in this feature as well.

**Comment by Alex-Tideman** [comment]
Removed ability to sort by start/end time due to server constraints.
