### ISSUE TITLE
Worflow details page header hyperlinks cause full page reload

### ISSUE THREAD

**Issue by BartXZX** [temporalio/ui#821]
**Describe the bug**
On the workflow-details page clicking any of the hyperlinks in the header causes a full reload of the website, instead of browsing inside the single page app. This is much slower than for example pressing "Back to Workflows" which is almost instant.

**To Reproduce**
1. Go to any workflow.
2. Click on any of the hyperlinks in the page header (see screenshot).
3. Notice it fully reloading the page.

**Expected behavior**
I would expect it to navigate inside of the single page app (if it even is that).

**Screenshots**
![image](https://user-images.githubusercontent.com/5583518/189621013-d9370de3-8ad7-4b2f-9cd8-9ed5334182e4.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome and Firefox
- Version Latest on both

**Comment by stevekinney** [comment]
@Alex-Tideman Can you confirm that this fixed now?
