### ISSUE TITLE
Decode Heartbeat Details similar to previous UI version

### ISSUE THREAD

**Issue by ivanvanderbyl** [temporalio/ui#861]
## Is your feature request related to a problem? Please describe.

First of all, I love the new UI, so fast! 

One thing I miss from the previous version is being able to inspect the latest heartbeat details for a given task to glance at progress. Currently it's showing the Base64 encoded payload:

<img width="731" alt="image" src="https://user-images.githubusercontent.com/24278/193479767-9d672d61-4e05-467c-b5ec-c3eb10b77178.png">

## Describe the solution you'd like

Decode the heartbeat detail if it can be rendered as a code block.

**Comment by Alex-Tideman** [comment]
Hey @ivanvanderbyl! Appreciate the feedback, we recently merged in a PR (https://github.com/temporalio/ui/pull/853) for decoding pending activities, so this will be part of the next release (which should be created today).
