### ISSUE TITLE
Support url rewrite for embed mode

### ISSUE THREAD

**Issue by diddowill** [temporalio/ui#911]
## Is your feature request related to a problem? Please describe.
when temporal is introduced in a business project，we probably need to integrate the temporal ui as part of the admin tool, which means temporal ui is embed into another web host. 

## Describe the solution you'd like
In this case we need to rewrite temporal request urls with a prefix identifier, and let those requested be routed to the actual temporal ui service. 
For example, with a configured prefix "temporal-ui", the  normal url "/namespaces/default/workflows" would become "/temporal-ui/namespaces/default/workflows". All the resource references should follow this rule. 

## Describe alternatives you've considered
I tried replacing the resource references in a reverse proxy, and found theres are different patterns need to be matched in html and js scripts. Even though we can make it work eventually, I do not think that is a maintainable solution.

**Comment by feedmeapples** [comment]
this is supported though you will want to build your own image https://github.com/temporalio/ui-server/tree/main/docker#serve-ui-under-a-sub-path

**Comment by manitgupta** [comment]
Hello, is this available when running Temporal using the golang server package or when using the temporal cli to run `temporal start-dev`?
