### ISSUE TITLE
Add reset button to the UI

### ISSUE THREAD

**Issue by antmendoza** [temporalio/ui#957]
## Is your feature request related to a problem? Please describe.

It would be nice to have the possibility to reset workflows from the UI (nowadays this is only possible with tctl and via sdk-api)

**Comment by gsagrawal** [comment]
It would be great to have this feature on UI. As there are cases when we want to retry our failed workflows (and activities) on production. 
To use tctl, we would have to share client certificates (and it won't have any kind of audit logs)

**Comment by sepehr500** [comment]
This would be great for us as well. Would allow non technical folk to rerun workflows

**Comment by aybabtme** [comment]
This is also something that would help us tremendously, even though my team is all technical and plenty capable of running CLI tools. However, our production systems are all sealed off and getting shell access to `tctl` and network access to the temporal server isn't easy. On the other hand, we can easily expose UIs behind an auth gateway (such as Okta) and get authz and authn and an audit log.

Reseting workflows is something core to our desire for Temporal: it enables us to ship frequently and rapidly with confidence, knowing that we can fix bugs for customers using Temporal's reset feature. However this is much harder when the feature isn't readily available in the UI, where most of our debugging story occurs.

**Comment by Alex-Tideman** [comment]
Feature is done.
